// src/pages/Community.jsx
import React, { useState, useEffect } from "react";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { FaPlus, FaTimes, FaUser, FaClock, FaHeart, FaComment, FaPaperPlane } from "react-icons/fa";

function Community() {
  const [posts, setPosts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  // Comments mapping: { [postId]: [comments_list] }
  const [commentsMap, setCommentsMap] = useState({});
  // Expanded posts mapping: { [postId]: boolean }
  const [expandedComments, setExpandedComments] = useState({});
  // New comment inputs mapping: { [postId]: { author_name, author_email, content } }
  const [newCommentInputs, setNewCommentInputs] = useState({});

  // Main Post Form State
  const [formData, setFormData] = useState({
    author_name: "",
    author_email: "",
    title: "",
    content: ""
  });

  const fetchApprovedPosts = async () => {
    try {
      const response = await fetch("/api/posts");
      if (response.ok) {
        const data = await response.json();
        setPosts(data);
      }
    } catch (err) {
      console.error("Error fetching approved posts:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchApprovedPosts();
  }, []);

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!formData.author_name || !formData.author_email || !formData.title || !formData.content) {
      alert("Please fill in all fields.");
      return;
    }

    setSubmitting(true);
    try {
      const response = await fetch("/api/posts", {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify(formData)
      });

      const data = await response.json();
      if (!response.ok) {
        throw new Error(data.error || "Failed to submit post");
      }

      alert("Post submitted successfully! It will appear on the feed once approved by an admin.");
      setFormData({
        author_name: "",
        author_email: "",
        title: "",
        content: ""
      });
      setShowModal(false);
      fetchApprovedPosts();
    } catch (err) {
      alert(err.message);
    } finally {
      setSubmitting(false);
    }
  };

  // Like a post
  const handleLikePost = async (postId) => {
    try {
      const response = await fetch(`/api/posts/${postId}/like`, {
        method: "POST"
      });
      if (response.ok) {
        const data = await response.json();
        // Update local state for likes count
        setPosts(prevPosts =>
          prevPosts.map(p => (p.id === postId ? { ...p, likes: data.likes } : p))
        );
      }
    } catch (err) {
      console.error("Error liking post:", err);
    }
  };

  // Toggle comments expand
  const handleToggleComments = async (postId) => {
    const isExpanded = !expandedComments[postId];
    setExpandedComments(prev => ({ ...prev, [postId]: isExpanded }));

    if (isExpanded) {
      fetchComments(postId);
    }
  };

  // Fetch comments
  const fetchComments = async (postId) => {
    try {
      const response = await fetch(`/api/posts/${postId}/comments`);
      if (response.ok) {
        const data = await response.json();
        setCommentsMap(prev => ({ ...prev, [postId]: data }));
      }
    } catch (err) {
      console.error("Error fetching comments:", err);
    }
  };

  // Comment inputs change handler
  const handleCommentInputChange = (postId, field, value) => {
    setNewCommentInputs(prev => ({
      ...prev,
      [postId]: {
        ...prev[postId],
        [field]: value
      }
    }));
  };

  // Submit comment
  const handleSubmitComment = async (e, postId) => {
    e.preventDefault();
    const commentInput = newCommentInputs[postId] || {};
    const { author_name, author_email, content } = commentInput;

    if (!author_name || !author_email || !content) {
      alert("Please fill in all comment fields.");
      return;
    }

    try {
      const response = await fetch(`/api/posts/${postId}/comments`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({ author_name, author_email, content })
      });

      if (!response.ok) {
        throw new Error("Failed to post comment");
      }

      // Reset input form
      setNewCommentInputs(prev => ({
        ...prev,
        [postId]: {
          author_name: "",
          author_email: "",
          content: ""
        }
      }));

      // Refresh comments
      fetchComments(postId);
    } catch (err) {
      alert(err.message);
    }
  };

  return (
    <div className="bg-slate-50 min-h-screen flex flex-col justify-between">
      <div>
        <Navbar />

        {/* HERO HEADER */}
        <header className="bg-black text-white py-16 md:py-24 px-5 md:px-10 text-center relative overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-r from-indigo-500/10 via-transparent to-red-500/10 opacity-70"></div>
          <div className="max-w-4xl mx-auto relative z-10 space-y-6">
            <span className="text-[10px] bg-red-650 text-white font-extrabold tracking-widest uppercase px-3 py-1 rounded-full">
              Academy Forum
            </span>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-black tracking-tight leading-none">
              Divijix Community Hub
            </h1>
            <p className="text-slate-400 text-sm md:text-base max-w-xl mx-auto leading-6">
              Share tech ideas, ask coding questions, and discuss cutting-edge AI technologies with fellow learners.
            </p>
            <div className="pt-4">
              <button
                onClick={() => setShowModal(true)}
                className="inline-flex items-center gap-2 bg-red-600 hover:bg-red-700 text-white font-bold text-sm px-7 py-4 rounded-xl transition shadow-lg shadow-red-600/10"
              >
                <FaPlus /> Write a Post
              </button>
            </div>
          </div>
        </header>

        {/* POSTS LISTING */}
        <main className="max-w-4xl mx-auto px-5 py-12 md:py-16">
          {loading ? (
            <div className="flex justify-center items-center py-20">
              <div className="animate-spin rounded-full h-10 w-10 border-t-2 border-b-2 border-indigo-650"></div>
            </div>
          ) : posts.length === 0 ? (
            <div className="bg-white rounded-3xl border border-slate-100 p-12 text-center shadow-md">
              <h3 className="text-xl font-bold text-slate-800 mb-2">No posts available yet</h3>
              <p className="text-slate-500 text-xs mb-6 max-w-sm mx-auto leading-5">
                Be the first to start a conversation! Submit a post detailing your AI projects or coding queries.
              </p>
              <button
                onClick={() => setShowModal(true)}
                className="bg-black hover:bg-slate-800 text-white text-xs font-bold px-6 py-3 rounded-lg transition"
              >
                Write First Post
              </button>
            </div>
          ) : (
            <div className="space-y-6">
              {posts.map((post) => {
                const isExpanded = expandedComments[post.id];
                const comments = commentsMap[post.id] || [];
                const cInput = newCommentInputs[post.id] || { author_name: "", author_email: "", content: "" };

                return (
                  <div
                    key={post.id}
                    className="bg-white rounded-[2rem] border border-slate-100 p-6 md:p-8 shadow-md hover:shadow-lg transition duration-300"
                  >
                    <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-50 pb-4 mb-4">
                      <div className="flex items-center gap-3">
                        <div className="w-9 h-9 rounded-full bg-indigo-50 text-indigo-650 flex items-center justify-center font-bold text-xs shrink-0">
                          {post.author_name.charAt(0)}
                        </div>
                        <div>
                          <h4 className="font-bold text-slate-800 text-sm leading-none">{post.author_name}</h4>
                          <span className="text-[10px] text-slate-400 font-semibold">{post.author_email}</span>
                        </div>
                      </div>
                      <div className="flex items-center gap-1.5 text-[10px] text-slate-400 font-semibold">
                        <FaClock />
                        <span>{new Date(post.created_at).toLocaleDateString(undefined, { dateStyle: 'medium' })}</span>
                      </div>
                    </div>

                    <h3 className="text-lg md:text-xl font-extrabold text-slate-900 mb-3">{post.title}</h3>
                    <p className="text-slate-600 text-xs md:text-sm leading-6 whitespace-pre-wrap mb-6">{post.content}</p>

                    {/* POST INTERACTIONS */}
                    <div className="flex items-center gap-4 border-t border-slate-50 pt-4 text-xs font-bold">
                      <button
                        onClick={() => handleLikePost(post.id)}
                        className="flex items-center gap-1.5 text-slate-500 hover:text-red-500 transition-colors"
                      >
                        <FaHeart className="text-red-400" />
                        <span>{post.likes || 0} Likes</span>
                      </button>
                      <button
                        onClick={() => handleToggleComments(post.id)}
                        className="flex items-center gap-1.5 text-slate-500 hover:text-indigo-650 transition-colors"
                      >
                        <FaComment className="text-indigo-400" />
                        <span>{isExpanded ? "Hide Discussions" : "Discussions"}</span>
                      </button>
                    </div>

                    {/* COMMENTS LIST & FORM */}
                    {isExpanded && (
                      <div className="mt-6 border-t border-slate-100 pt-6 space-y-6">
                        {/* Comments Feed */}
                        <div className="space-y-4">
                          <h4 className="text-[10px] font-black uppercase tracking-wider text-slate-450">Student Discussions</h4>
                          {comments.length === 0 ? (
                            <p className="text-xs text-slate-400 italic">No replies yet. Start the discussion below.</p>
                          ) : (
                            <div className="space-y-4 pl-3 border-l-2 border-slate-100">
                              {comments.map((comment) => (
                                <div key={comment.id} className="space-y-1">
                                  <div className="flex items-center gap-2 text-xs">
                                    <span className="font-bold text-slate-800">{comment.author_name}</span>
                                    <span className="text-[10px] text-slate-400">
                                      {new Date(comment.created_at).toLocaleDateString(undefined, { dateStyle: 'short' })}
                                    </span>
                                  </div>
                                  <p className="text-slate-600 text-xs leading-5">{comment.content}</p>
                                </div>
                              ))}
                            </div>
                          )}
                        </div>

                        {/* Comment Form */}
                        <form onSubmit={(e) => handleSubmitComment(e, post.id)} className="space-y-3 bg-slate-50 p-4 rounded-2xl border border-slate-100/50">
                          <p className="text-[10px] font-black uppercase tracking-wider text-slate-450">Reply to this thread</p>
                          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                            <input
                              type="text"
                              placeholder="Your Name"
                              value={cInput.author_name || ""}
                              onChange={(e) => handleCommentInputChange(post.id, "author_name", e.target.value)}
                              className="border border-slate-200 outline-none rounded-xl p-2.5 text-xs bg-white"
                              required
                            />
                            <input
                              type="email"
                              placeholder="Your Email"
                              value={cInput.author_email || ""}
                              onChange={(e) => handleCommentInputChange(post.id, "author_email", e.target.value)}
                              className="border border-slate-200 outline-none rounded-xl p-2.5 text-xs bg-white"
                              required
                            />
                          </div>
                          <div className="relative">
                            <textarea
                              placeholder="Add to the discussion..."
                              value={cInput.content || ""}
                              onChange={(e) => handleCommentInputChange(post.id, "content", e.target.value)}
                              rows="2"
                              className="w-full border border-slate-200 outline-none rounded-xl p-3 text-xs bg-white resize-none pr-10"
                              required
                            ></textarea>
                            <button
                              type="submit"
                              className="absolute right-3.5 bottom-4 p-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg transition"
                            >
                              <FaPaperPlane size={10} />
                            </button>
                          </div>
                        </form>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          )}
        </main>
      </div>

      <Footer />

      {/* CREATE POST MODAL */}
      {showModal && (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white w-full max-w-xl rounded-[2rem] p-8 shadow-2xl relative border border-slate-100 max-h-[90vh] overflow-y-auto">
            <button
              onClick={() => setShowModal(false)}
              className="absolute top-6 right-6 p-2 text-slate-400 hover:text-slate-700 hover:bg-slate-100 rounded-full transition"
            >
              <FaTimes size={18} />
            </button>

            <div className="mb-6">
              <h3 className="text-2xl font-extrabold text-slate-850">Write a Community Post</h3>
              <p className="text-xs text-slate-400 mt-1">Submit your post. It will go live once reviewed by an admin.</p>
            </div>

            <form onSubmit={handleSubmit} className="space-y-5 text-left">
              {/* Author Name */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-slate-550 uppercase tracking-wide">Your Name</label>
                <input
                  type="text"
                  name="author_name"
                  value={formData.author_name}
                  onChange={handleChange}
                  placeholder="Enter your name"
                  className="w-full border border-slate-200 focus:border-indigo-600 focus:ring-1 focus:ring-indigo-600 outline-none rounded-xl p-3.5 text-sm transition"
                  required
                />
              </div>

              {/* Author Email */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-slate-550 uppercase tracking-wide">Your Email</label>
                <input
                  type="email"
                  name="author_email"
                  value={formData.author_email}
                  onChange={handleChange}
                  placeholder="Enter your email"
                  className="w-full border border-slate-200 focus:border-indigo-600 focus:ring-1 focus:ring-indigo-600 outline-none rounded-xl p-3.5 text-sm transition"
                  required
                />
              </div>

              {/* Post Title */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-slate-550 uppercase tracking-wide">Title</label>
                <input
                  type="text"
                  name="title"
                  value={formData.title}
                  onChange={handleChange}
                  placeholder="e.g. Building an autonomous customer support agent"
                  className="w-full border border-slate-200 focus:border-indigo-600 focus:ring-1 focus:ring-indigo-600 outline-none rounded-xl p-3.5 text-sm transition"
                  required
                />
              </div>

              {/* Post Content */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-slate-550 uppercase tracking-wide">Content</label>
                <textarea
                  name="content"
                  value={formData.content}
                  onChange={handleChange}
                  placeholder="Describe your tech stack, post code snippets, or ask questions here..."
                  rows="5"
                  className="w-full border border-slate-200 focus:border-indigo-600 focus:ring-1 focus:ring-indigo-600 outline-none rounded-xl p-3.5 text-sm transition resize-none"
                  required
                ></textarea>
              </div>

              {/* Actions */}
              <div className="flex justify-end gap-3 pt-4 border-t border-slate-100">
                <button
                  type="button"
                  onClick={() => setShowModal(false)}
                  className="border border-slate-200 hover:bg-slate-50 text-slate-700 text-xs font-bold px-5 py-3 rounded-xl transition"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={submitting}
                  className="bg-indigo-650 hover:bg-indigo-700 text-white text-xs font-bold px-6 py-3 rounded-xl transition shadow-md shadow-indigo-600/10"
                >
                  {submitting ? "Submitting..." : "Submit Post"}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}

export default Community;

// src/app/pages/community/community.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { NavbarComponent } from '../../components/navbar/navbar.component';
import { FooterComponent } from '../../components/footer/footer.component';
import { ApiService } from '../../services/api.service';

interface Post {
  id: number;
  author_name: string;
  author_email: string;
  title: string;
  content: string;
  likes: number;
  created_at: string;
}

interface PostComment {
  id: number;
  author_name: string;
  author_email: string;
  content: string;
  created_at: string;
}

@Component({
  selector: 'app-community',
  standalone: true,
  imports: [NavbarComponent, FooterComponent, CommonModule, ReactiveFormsModule],
  templateUrl: './community.component.html'
})
export class CommunityComponent implements OnInit {
  private apiService = inject(ApiService);
  private fb = inject(FormBuilder);

  posts: Post[] = [];
  loading = true;
  showModal = false;
  submitting = false;

  commentsMap: Record<number, PostComment[]> = {};
  expandedComments: Record<number, boolean> = {};
  commentForms: Record<number, FormGroup> = {};

  postForm: FormGroup = this.fb.group({
    author_name: ['', Validators.required],
    author_email: ['', [Validators.required, Validators.email]],
    title: ['', Validators.required],
    content: ['', Validators.required]
  });

  ngOnInit() {
    this.fetchApprovedPosts();
  }

  fetchApprovedPosts() {
    this.apiService.get<Post[]>('/api/posts').subscribe({
      next: (data) => {
        this.posts = data;
        this.loading = false;
      },
      error: (err) => {
        console.error('Error fetching approved posts:', err);
        this.loading = false;
      }
    });
  }

  handleSubmit() {
    if (this.postForm.invalid) {
      this.postForm.markAllAsTouched();
      return;
    }

    this.submitting = true;
    this.apiService.post<any>('/api/posts', this.postForm.value).subscribe({
      next: () => {
        alert("Post submitted successfully! It will appear on the feed once approved by an admin.");
        this.postForm.reset();
        this.showModal = false;
        this.submitting = false;
        this.fetchApprovedPosts();
      },
      error: (err) => {
        alert(err.error?.error || "Failed to submit post");
        this.submitting = false;
      }
    });
  }

  handleLikePost(postId: number) {
    this.apiService.post<any>(`/api/posts/${postId}/like`, {}).subscribe({
      next: (data) => {
        this.posts = this.posts.map((p) =>
          p.id === postId ? { ...p, likes: data.likes } : p
        );
      },
      error: (err) => {
        console.error("Error liking post:", err);
      }
    });
  }

  handleToggleComments(postId: number) {
    const isExpanded = !this.expandedComments[postId];
    this.expandedComments[postId] = isExpanded;

    if (isExpanded) {
      this.fetchComments(postId);
    }
  }

  fetchComments(postId: number) {
    this.apiService.get<PostComment[]>(`/api/posts/${postId}/comments`).subscribe({
      next: (data) => {
        this.commentsMap[postId] = data;
      },
      error: (err) => {
        console.error("Error fetching comments:", err);
      }
    });
  }

  getCommentForm(postId: number): FormGroup {
    if (!this.commentForms[postId]) {
      this.commentForms[postId] = this.fb.group({
        author_name: ['', Validators.required],
        author_email: ['', [Validators.required, Validators.email]],
        content: ['', Validators.required]
      });
    }
    return this.commentForms[postId];
  }

  handleSubmitComment(postId: number) {
    const form = this.getCommentForm(postId);
    if (form.invalid) {
      form.markAllAsTouched();
      return;
    }

    this.apiService.post<any>(`/api/posts/${postId}/comments`, form.value).subscribe({
      next: () => {
        form.reset();
        this.fetchComments(postId);
      },
      error: (err) => {
        alert(err.error?.error || "Failed to post comment");
      }
    });
  }

  formatDate(dateStr: string): string {
    return new Date(dateStr).toLocaleDateString(undefined, { dateStyle: 'medium' });
  }

  formatDateShort(dateStr: string): string {
    return new Date(dateStr).toLocaleDateString(undefined, { dateStyle: 'short' });
  }
}

<div
  class="bg-slate-50 dark:bg-[#080809] min-h-screen flex flex-col justify-between text-gray-800 dark:text-white transition-colors duration-250">
  <div>
    <app-navbar />

    <!-- HERO HEADER -->
    <header class="bg-black text-white py-16 md:py-24 px-5 md:px-10 text-center relative overflow-hidden">
      <div class="absolute inset-0 bg-gradient-to-r from-red-500/10 via-transparent to-zinc-500/10 opacity-70"></div>
      <div class="max-w-4xl mx-auto relative z-10 space-y-6">
        <span class="text-[10px] bg-red-600 text-white font-extrabold tracking-widest uppercase px-3 py-1 rounded-full">
          Academy Forum
        </span>
        <h1 class="text-4xl md:text-5xl lg:text-6xl font-black tracking-tight leading-none">
          Divijix Community Hub
        </h1>
        <p class="text-slate-400 text-sm md:text-base max-w-xl mx-auto leading-6">
          Share tech ideas, ask coding questions, and discuss cutting-edge AI technologies with fellow learners.
        </p>
        <div class="pt-4">
          <button (click)="showModal = true"
            class="inline-flex items-center gap-2 bg-red-600 hover:bg-red-500 text-white font-bold text-sm px-7 py-4 rounded-xl transition shadow-lg shadow-red-600/10 border-none cursor-pointer">
            <i class="fa-solid fa-plus"></i> Write a Post
          </button>
        </div>
      </div>
    </header>

    <!-- POSTS LISTING -->
    <main class="max-w-4xl mx-auto px-5 py-12 md:py-16">
      @if (loading) {
      <div class="flex justify-center items-center py-20">
        <div class="animate-spin rounded-full h-10 w-10 border-t-2 border-b-2 border-red-600"></div>
      </div>
      } @else if (posts.length === 0) {
      <div
        class="bg-white dark:bg-[#141416] rounded-3xl border border-slate-100 dark:border-zinc-800 p-12 text-center shadow-md">
        <h3 class="text-xl font-bold text-slate-800 dark:text-white mb-2">No posts available yet</h3>
        <p class="text-slate-500 dark:text-zinc-400 text-xs mb-6 max-w-sm mx-auto leading-5">
          Be the first to start a conversation! Submit a post detailing your AI projects or coding queries.
        </p>
        <button (click)="showModal = true"
          class="bg-black dark:bg-white dark:text-black hover:bg-slate-800 text-xs font-bold px-6 py-3 rounded-lg transition border-none cursor-pointer">
          Write First Post
        </button>
      </div>
      } @else {
      <div class="space-y-6">
        @for (post of posts; track post.id) {
        <div
          class="bg-white dark:bg-[#141416] rounded-[2rem] border border-slate-100 dark:border-zinc-800 p-6 md:p-8 shadow-md hover:shadow-lg transition duration-300">
          <div
            class="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-50 dark:border-zinc-800/80 pb-4 mb-4">
            <div class="flex items-center gap-3">
              <div
                class="w-9 h-9 rounded-full bg-red-50 dark:bg-zinc-800 text-red-600 dark:text-red-400 flex items-center justify-center font-bold text-xs shrink-0 uppercase">
                {{post.author_name.charAt(0)}}
              </div>
              <div class="text-left">
                <h4 class="font-bold text-slate-800 dark:text-white text-sm leading-none">{{post.author_name}}</h4>
                <span class="text-[10px] text-slate-400 dark:text-zinc-500 font-semibold">{{post.author_email}}</span>
              </div>
            </div>
            <div class="flex items-center gap-1.5 text-[10px] text-slate-455 dark:text-zinc-500 font-semibold">
              <i class="fa-regular fa-clock"></i>
              <span>{{formatDate(post.created_at)}}</span>
            </div>
          </div>

          <h3 class="text-lg md:text-xl font-extrabold text-slate-900 dark:text-white mb-3 text-left">{{post.title}}
          </h3>
          <p class="text-slate-600 dark:text-zinc-300 text-xs md:text-sm leading-6 whitespace-pre-wrap mb-6 text-left">
            {{post.content}}</p>

          <!-- POST INTERACTIONS -->
          <div class="flex items-center gap-4 border-t border-slate-50 dark:border-zinc-800/80 pt-4 text-xs font-bold">
            <button (click)="handleLikePost(post.id)"
              class="flex items-center gap-1.5 text-slate-500 dark:text-zinc-450 hover:text-red-500 transition-colors border-none bg-transparent cursor-pointer">
              <i class="fa-solid fa-heart text-red-500"></i>
              <span>{{post.likes || 0}} Likes</span>
            </button>
            <button (click)="handleToggleComments(post.id)"
              class="flex items-center gap-1.5 text-slate-500 dark:text-zinc-450 hover:text-red-550 transition-colors border-none bg-transparent cursor-pointer">
              <i class="fa-solid fa-comment text-red-400 dark:text-red-500"></i>
              <span>{{expandedComments[post.id] ? "Hide Discussions" : "Discussions"}}</span>
            </button>
          </div>

          <!-- COMMENTS LIST & FORM -->
          @if (expandedComments[post.id]) {
          <div class="mt-6 border-t border-slate-100 dark:border-zinc-800 pt-6 space-y-6">
            <!-- Comments Feed -->
            <div class="space-y-4">
              <h4 class="text-[10px] font-black uppercase tracking-wider text-slate-400 text-left">Student Discussions
              </h4>
              @if (!commentsMap[post.id] || commentsMap[post.id].length === 0) {
              <p class="text-xs text-slate-400 italic text-left">No replies yet. Start the discussion below.</p>
              } @else {
              <div class="space-y-4 pl-3 border-l-2 border-slate-100 dark:border-zinc-800 text-left">
                @for (comment of commentsMap[post.id]; track comment.id) {
                <div class="space-y-1">
                  <div class="flex items-center gap-2 text-xs">
                    <span class="font-bold text-slate-800 dark:text-white">{{comment.author_name}}</span>
                    <span class="text-[10px] text-slate-400 dark:text-zinc-500">
                      {{formatDateShort(comment.created_at)}}
                    </span>
                  </div>
                  <p class="text-slate-600 dark:text-zinc-350 text-xs leading-5">{{comment.content}}</p>
                </div>
                }
              </div>
              }
            </div>

            <!-- Comment Form -->
            <form [formGroup]="getCommentForm(post.id)" (ngSubmit)="handleSubmitComment(post.id)"
              class="space-y-3 bg-slate-50 dark:bg-[#0D0D0E] p-4 rounded-2xl border border-slate-100/50 dark:border-zinc-800/80">
              <p class="text-[10px] font-black uppercase tracking-wider text-slate-455 dark:text-zinc-400 text-left">
                Reply to this thread</p>
              <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div class="text-left">
                  <input type="text" placeholder="Your Name" formControlName="author_name"
                    class="w-full border border-slate-200 dark:border-zinc-800 outline-none rounded-xl p-2.5 text-xs bg-white dark:bg-[#141416] text-gray-800 dark:text-white" />
                  @if (getCommentForm(post.id).get('author_name')?.touched && getCommentForm(post.id).get('author_name')?.errors?.['required']) {
                    <p class="text-red-500 text-[10px] mt-0.5 text-left">Name is required.</p>
                  }
                </div>
                <div class="text-left">
                  <input type="email" placeholder="Your Email" formControlName="author_email"
                    class="w-full border border-slate-200 dark:border-zinc-800 outline-none rounded-xl p-2.5 text-xs bg-white dark:bg-[#141416] text-gray-800 dark:text-white" />
                  @if (getCommentForm(post.id).get('author_email')?.touched && getCommentForm(post.id).get('author_email')?.errors) {
                    <p class="text-red-500 text-[10px] mt-0.5 text-left font-medium">
                      @if (getCommentForm(post.id).get('author_email')?.errors?.['required']) {
                        Email is required.
                      } @else if (getCommentForm(post.id).get('author_email')?.errors?.['email']) {
                        Invalid email format.
                      }
                    </p>
                  }
                </div>
              </div>
              <div class="text-left">
                <div class="relative">
                  <textarea placeholder="Add to the discussion..." formControlName="content" rows="2"
                    class="w-full border border-slate-200 dark:border-zinc-800 outline-none rounded-xl p-3 text-xs bg-white dark:bg-[#141416] text-gray-800 dark:text-white resize-none pr-10"></textarea>
                  <button type="submit"
                    class="absolute right-3.5 bottom-4 p-2 bg-red-600 hover:bg-red-500 text-white rounded-lg transition border-none cursor-pointer">
                    <i class="fa-solid fa-paper-plane text-[10px]"></i>
                  </button>
                </div>
                @if (getCommentForm(post.id).get('content')?.touched && getCommentForm(post.id).get('content')?.errors?.['required']) {
                  <p class="text-red-500 text-[10px] mt-0.5 text-left">Comment content is required.</p>
                }
              </div>
            </form>
          </div>
          }
        </div>
        }
      </div>
      }
    </main>
  </div>

  <app-footer />

  <!-- CREATE POST MODAL -->
  @if (showModal) {
  <div class="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
    <div
      class="bg-white dark:bg-[#141416] w-full max-w-xl rounded-[2rem] p-8 shadow-2xl relative border border-slate-100 dark:border-zinc-800 max-h-[90vh] overflow-y-auto">
      <button (click)="showModal = false"
        class="absolute top-6 right-6 p-2 text-slate-400 hover:text-slate-700 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-zinc-800 rounded-full transition border-none bg-transparent cursor-pointer">
        <i class="fa-solid fa-xmark text-lg"></i>
      </button>

      <div class="mb-6 text-left">
        <h3 class="text-2xl font-extrabold text-slate-850 dark:text-white">Write a Community Post</h3>
        <p class="text-xs text-slate-400 dark:text-zinc-400 mt-1">Submit your post. It will go live once reviewed by an
          admin.</p>
      </div>

      <form [formGroup]="postForm" (ngSubmit)="handleSubmit()" class="space-y-5 text-left">
        <!-- Author Name -->
        <div class="space-y-1.5">
          <label class="text-xs font-bold text-slate-550 dark:text-zinc-400 uppercase tracking-wide">Your Name</label>
          <input type="text" formControlName="author_name" placeholder="Enter your name"
            class="w-full bg-white dark:bg-[#0D0D0E] border border-slate-200 dark:border-zinc-800 focus:border-red-600 focus:ring-1 focus:ring-red-500 outline-none rounded-xl p-3.5 text-sm text-gray-855 dark:text-white placeholder-gray-400" />
          @if (postForm.get('author_name')?.touched && postForm.get('author_name')?.errors?.['required']) {
            <p class="text-red-500 text-xs mt-1">Name is required.</p>
          }
        </div>

        <!-- Author Email -->
        <div class="space-y-1.5">
          <label class="text-xs font-bold text-slate-555 dark:text-zinc-400 uppercase tracking-wide">Your Email</label>
          <input type="email" formControlName="author_email" placeholder="Enter your email"
            class="w-full bg-white dark:bg-[#0D0D0E] border border-slate-200 dark:border-zinc-800 focus:border-red-650 focus:ring-1 focus:ring-red-500 outline-none rounded-xl p-3.5 text-sm text-gray-855 dark:text-white placeholder-gray-400" />
          @if (postForm.get('author_email')?.touched && postForm.get('author_email')?.errors) {
            <p class="text-red-500 text-xs mt-1">
              @if (postForm.get('author_email')?.errors?.['required']) {
                Email is required.
              } @else if (postForm.get('author_email')?.errors?.['email']) {
                Please enter a valid email address.
              }
            </p>
          }
        </div>

        <!-- Post Title -->
        <div class="space-y-1.5">
          <label class="text-xs font-bold text-slate-555 dark:text-zinc-400 uppercase tracking-wide">Title</label>
          <input type="text" formControlName="title"
            placeholder="e.g. Building an autonomous customer support agent"
            class="w-full bg-white dark:bg-[#0D0D0E] border border-slate-200 dark:border-zinc-800 focus:border-red-600 focus:ring-1 focus:ring-red-500 outline-none rounded-xl p-3.5 text-sm text-gray-855 dark:text-white placeholder-gray-400" />
          @if (postForm.get('title')?.touched && postForm.get('title')?.errors?.['required']) {
            <p class="text-red-500 text-xs mt-1">Title is required.</p>
          }
        </div>

        <!-- Post Content -->
        <div class="space-y-1.5">
          <label class="text-xs font-bold text-slate-555 dark:text-zinc-400 uppercase tracking-wide">Content</label>
          <textarea formControlName="content"
            placeholder="Describe your tech stack, post code snippets, or ask questions here..." rows="5"
            class="w-full bg-white dark:bg-[#0D0D0E] border border-slate-200 dark:border-zinc-800 focus:border-red-600 focus:ring-1 focus:ring-red-500 outline-none rounded-xl p-3.5 text-sm text-gray-855 dark:text-white placeholder-gray-400 resize-none"></textarea>
          @if (postForm.get('content')?.touched && postForm.get('content')?.errors?.['required']) {
            <p class="text-red-500 text-xs mt-1">Content is required.</p>
          }
        </div>

        <!-- Actions -->
        <div class="flex justify-end gap-3 pt-4 border-t border-slate-100 dark:border-zinc-800">
          <button type="button" (click)="showModal = false"
            class="border border-slate-200 dark:border-zinc-800 hover:bg-slate-50 dark:hover:bg-zinc-800 text-slate-700 dark:text-zinc-300 text-xs font-bold px-5 py-3 rounded-xl transition bg-transparent cursor-pointer">
            Cancel
          </button>
          <button type="submit" [disabled]="submitting"
            class="bg-red-650 hover:bg-red-700 text-white text-xs font-bold px-6 py-3 rounded-xl transition shadow-md shadow-indigo-600/10 border-none cursor-pointer disabled:opacity-50">
            {{submitting ? 'Submitting...' : 'Submit Post'}}
          </button>
        </div>
      </form>
    </div>
  </div>
  }
</div>
