// src/components/Navbar.jsx
import React, { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { FaBars, FaTimes } from "react-icons/fa";

function Navbar() {
  /* MOBILE MENU */
  const [menuOpen, setMenuOpen] = useState(false);

  /* FORM MODAL */
  const [showForm, setShowForm] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  /* AUTH STATE */
  const [isLoggedIn, setIsLoggedIn] = useState(false);

  useEffect(() => {
    const token = localStorage.getItem("token");
    const user = localStorage.getItem("user");
    if (token && user) {
      setIsLoggedIn(true);
    } else {
      setIsLoggedIn(false);
    }
  }, []);

  /* FORM STATE */
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    phone: "",
    linkedin: "",
    college: "",
    passout: "",
    resume: null
  });

  /* HANDLE INPUT */
  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value
    });
  };

  /* HANDLE FILE */
  const handleFileChange = (e) => {
    setFormData({
      ...formData,
      resume: e.target.files[0]
    });
  };

  /* HANDLE SUBMIT */
  const handleSubmit = async (e) => {
    e.preventDefault();
    setSubmitting(true);

    try {
      const response = await fetch("/api/applications", {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          name: formData.name,
          email: formData.email,
          phone: formData.phone,
          linkedin: formData.linkedin,
          college: formData.college,
          passout: formData.passout
        })
      });

      const data = await response.json();
      if (!response.ok) {
        throw new Error(data.error || "Failed to submit application");
      }

      alert("Application Submitted Successfully");
      setFormData({
        name: "",
        email: "",
        phone: "",
        linkedin: "",
        college: "",
        passout: "",
        resume: null
      });
      setShowForm(false);
    } catch (err) {
      alert(err.message);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <>
      {/* NAVBAR */}
      <nav className="flex justify-between items-center px-5 md:px-10 py-5 md:py-6 bg-white shadow-sm sticky top-0 z-50">
        {/* LOGO */}
        <Link to="/" className="text-2xl md:text-3xl font-bold hover:opacity-90 transition">
          Divijix academy
        </Link>

        {/* DESKTOP MENU */}
        <ul className="hidden md:flex gap-10 text-gray-600 font-medium items-center">
          <li className="hover:text-red-600 transition cursor-pointer">
            <Link to="/">Home</Link>
          </li>
          <li className="hover:text-red-600 transition cursor-pointer">
            <Link to="/about">About</Link>
          </li>
          <li className="hover:text-red-600 transition cursor-pointer">
            <Link to="/courses">Courses</Link>
          </li>
          <li className="hover:text-red-600 transition cursor-pointer">
            <Link to="/research">Research</Link>
          </li>
          <li className="hover:text-red-600 transition cursor-pointer">
            <Link to="/community">Community</Link>
          </li>
          <li className="hover:text-red-600 transition cursor-pointer">
            <Link to="/contact">Contact</Link>
          </li>
          {isLoggedIn ? (
            <li className="hover:text-red-600 transition cursor-pointer">
              <Link to="/dashboard" className="bg-black text-white px-4 py-2 rounded-xl text-sm font-semibold hover:bg-gray-800 transition">
                Dashboard
              </Link>
            </li>
          ) : (
            <li className="hover:text-red-600 transition cursor-pointer">
              <Link to="/login" className="bg-gray-100 text-gray-800 px-4 py-2 rounded-xl text-sm font-semibold hover:bg-gray-200 transition">
                Login
              </Link>
            </li>
          )}
        </ul>

        {/* DESKTOP BUTTON */}
        <button
          onClick={() => setShowForm(true)}
          className="hidden md:block bg-red-600 text-white px-6 py-3 rounded-xl hover:bg-red-700 transition duration-300 font-semibold text-sm"
        >
          Apply Now
        </button>

        {/* MOBILE MENU ICON */}
        <button
          className="md:hidden text-2xl"
          onClick={() => setMenuOpen(!menuOpen)}
        >
          {menuOpen ? <FaTimes /> : <FaBars />}
        </button>

        {/* MOBILE MENU */}
        <div
          className={`absolute top-[80px] left-0 w-full bg-white shadow-lg transition-all duration-300 md:hidden ${
            menuOpen ? "opacity-100 visible" : "opacity-0 invisible"
          }`}
        >
          <ul className="flex flex-col items-center gap-8 py-10 text-gray-700 font-medium">
            <li onClick={() => setMenuOpen(false)}>
              <Link to="/">Home</Link>
            </li>
            <li onClick={() => setMenuOpen(false)}>
              <Link to="/about">About</Link>
            </li>
            <li onClick={() => setMenuOpen(false)}>
              <Link to="/courses">Courses</Link>
            </li>
            <li onClick={() => setMenuOpen(false)}>
              <Link to="/research">Research</Link>
            </li>
            <li onClick={() => setMenuOpen(false)}>
              <Link to="/community">Community</Link>
            </li>
            <li onClick={() => setMenuOpen(false)}>
              <Link to="/contact">Contact</Link>
            </li>
            {isLoggedIn ? (
              <li onClick={() => setMenuOpen(false)}>
                <Link to="/dashboard">Dashboard</Link>
              </li>
            ) : (
              <li onClick={() => setMenuOpen(false)}>
                <Link to="/login">Login</Link>
              </li>
            )}
            <button
              onClick={() => {
                setShowForm(true);
                setMenuOpen(false);
              }}
              className="bg-red-600 text-white px-6 py-3 rounded-xl hover:bg-red-700 transition duration-300 text-sm font-semibold"
            >
              Apply Now
            </button>
          </ul>
        </div>
      </nav>

      {/* FORM MODAL */}
      {showForm && (
        <div className="fixed inset-0 bg-black/60 flex justify-center items-center z-50 px-4">
          <div className="bg-white w-full max-w-2xl rounded-3xl p-6 md:p-10 relative overflow-y-auto max-h-[90vh]">
            {/* CLOSE BUTTON */}
            <button
              onClick={() => setShowForm(false)}
              className="absolute top-5 right-5 text-2xl hover:text-gray-600 transition"
            >
              ✕
            </button>

            {/* TITLE */}
            <h1 className="text-3xl md:text-4xl font-bold mb-2">Apply Now</h1>
            <p className="text-gray-500 mb-8">Fill the application form to join Divijix Academy.</p>

            {/* FORM */}
            <form onSubmit={handleSubmit} className="space-y-6">
              {/* NAME */}
              <div className="text-left">
                <label className="block mb-2 font-medium text-sm text-gray-700">Full Name *</label>
                <input
                  type="text"
                  name="name"
                  value={formData.name}
                  onChange={handleChange}
                  placeholder="Enter your full name"
                  required
                  className="w-full border border-gray-300 rounded-xl px-5 py-4 outline-none focus:border-red-500 text-sm"
                />
              </div>

              {/* EMAIL */}
              <div className="text-left">
                <label className="block mb-2 font-medium text-sm text-gray-700">Email *</label>
                <input
                  type="email"
                  name="email"
                  value={formData.email}
                  onChange={handleChange}
                  placeholder="Enter your email"
                  required
                  className="w-full border border-gray-300 rounded-xl px-5 py-4 outline-none focus:border-red-500 text-sm"
                />
              </div>

              {/* PHONE */}
              <div className="text-left">
                <label className="block mb-2 font-medium text-sm text-gray-700">Phone Number *</label>
                <input
                  type="text"
                  name="phone"
                  value={formData.phone}
                  onChange={handleChange}
                  placeholder="+91 9876543210"
                  required
                  className="w-full border border-gray-300 rounded-xl px-5 py-4 outline-none focus:border-red-500 text-sm"
                />
              </div>

              {/* LINKEDIN */}
              <div className="text-left">
                <label className="block mb-2 font-medium text-sm text-gray-700">LinkedIn Profile *</label>
                <input
                  type="url"
                  name="linkedin"
                  value={formData.linkedin}
                  onChange={handleChange}
                  placeholder="https://linkedin.com/in/username"
                  required
                  className="w-full border border-gray-300 rounded-xl px-5 py-4 outline-none focus:border-red-500 text-sm"
                />
              </div>

              {/* COLLEGE */}
              <div className="text-left">
                <label className="block mb-2 font-medium text-sm text-gray-700">College Name *</label>
                <input
                  type="text"
                  name="college"
                  value={formData.college}
                  onChange={handleChange}
                  placeholder="Enter your college name"
                  required
                  className="w-full border border-gray-300 rounded-xl px-5 py-4 outline-none focus:border-red-500 text-sm"
                />
              </div>

              {/* PASSOUT YEAR */}
              <div className="text-left">
                <label className="block mb-2 font-medium text-sm text-gray-700">Passout Year *</label>
                <input
                  type="text"
                  name="passout"
                  value={formData.passout}
                  onChange={handleChange}
                  placeholder="2026"
                  required
                  className="w-full border border-gray-300 rounded-xl px-5 py-4 outline-none focus:border-red-500 text-sm"
                />
              </div>

              {/* SUBMIT BUTTON */}
              <button
                type="submit"
                disabled={submitting}
                className="w-full bg-red-600 text-white py-4 rounded-xl hover:bg-red-700 transition duration-300 font-semibold text-sm shadow-sm"
              >
                {submitting ? "Submitting Application..." : "Submit Application"}
              </button>
            </form>
          </div>
        </div>
      )}
    </>
  );
}

export default Navbar;

// src/app/components/navbar/navbar.component.ts
import { Component, inject } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ThemeService } from '../../services/theme.service';
import { AuthService } from '../../services/auth.service';
import { ApiService } from '../../services/api.service';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [RouterLink, RouterLinkActive, ReactiveFormsModule],
  templateUrl: './navbar.component.html'
})
export class NavbarComponent {
  themeService = inject(ThemeService);
  authService = inject(AuthService);
  private apiService = inject(ApiService);
  private fb = inject(FormBuilder);

  menuOpen = false;
  showForm = false;
  submitting = false;

  applyForm: FormGroup = this.fb.group({
    name: ['', Validators.required],
    email: ['', [Validators.required, Validators.email]],
    phone: ['', [Validators.required, Validators.pattern('^[0-9]{10}$')]],
    linkedin: ['', [Validators.required, Validators.pattern('^https?:\\/\\/(www\\.)?linkedin\\.com\\/.*$')]],
    college: ['', Validators.required],
    passout: ['', [Validators.required, Validators.pattern('^[0-9]{4}$')]]
  });

  openApplyModal() {
    this.showForm = true;
  }

  handleSubmit() {
    if (this.applyForm.invalid) {
      this.applyForm.markAllAsTouched();
      return;
    }

    this.submitting = true;
    this.apiService.post('/api/applications', this.applyForm.value).subscribe({
      next: () => {
        alert("Application Submitted Successfully");
        this.applyForm.reset();
        this.showForm = false;
        this.submitting = false;
      },
      error: (err) => {
        alert(err.error?.error || "Failed to submit application");
        this.submitting = false;
      }
    });
  }
}

<nav class="flex justify-between items-center px-5 md:px-10 py-5 md:py-6 bg-white dark:bg-[#0D0D0E]/85 border-b border-gray-100 dark:border-zinc-800/80 sticky top-0 z-50 text-gray-800 dark:text-white transition-colors duration-250 shadow-sm dark:shadow-lg">
  <!-- LOGO -->
  <a routerLink="/" class="text-2xl md:text-3xl font-bold hover:text-red-500 transition">
    Divijix academy
  </a>

  <!-- DESKTOP MENU -->
  <ul class="hidden md:flex gap-10 text-gray-650 dark:text-zinc-300 font-medium items-center">
    <li>
      <a routerLink="/" routerLinkActive="text-red-600 dark:text-red-500" [routerLinkActiveOptions]="{exact: true}" class="hover:text-red-655 dark:hover:text-red-500 transition cursor-pointer">Home</a>
    </li>
    <li>
      <a routerLink="/about" routerLinkActive="text-red-600 dark:text-red-500" class="hover:text-red-655 dark:hover:text-red-500 transition cursor-pointer">About</a>
    </li>
    <li>
      <a routerLink="/courses" routerLinkActive="text-red-600 dark:text-red-500" class="hover:text-red-655 dark:hover:text-red-500 transition cursor-pointer">Courses</a>
    </li>
    <li>
      <a routerLink="/Research" routerLinkActive="text-red-600 dark:text-red-500" class="hover:text-red-655 dark:hover:text-red-500 transition cursor-pointer">Research</a>
    </li>
    <li>
      <a routerLink="/community" routerLinkActive="text-red-600 dark:text-red-500" class="hover:text-red-655 dark:hover:text-red-500 transition cursor-pointer">Community</a>
    </li>
    <li>
      <a routerLink="/contact" routerLinkActive="text-red-600 dark:text-red-500" class="hover:text-red-655 dark:hover:text-red-500 transition cursor-pointer">Contact</a>
    </li>
    @if (authService.isLoggedIn()) {
      <li>
        <a routerLink="/dashboard" class="bg-black text-white dark:bg-white dark:text-black px-4 py-2 rounded-xl text-sm font-semibold hover:bg-gray-800 dark:hover:bg-zinc-200 transition">
          Dashboard
        </a>
      </li>
    } @else {
      <li>
        <a routerLink="/login" class="bg-gray-100 text-gray-855 dark:bg-zinc-800 dark:text-zinc-200 px-4 py-2 rounded-xl text-sm font-semibold hover:bg-gray-200 dark:hover:bg-zinc-700 transition">
          Login
        </a>
      </li>
    }
  </ul>

  <!-- DESKTOP ACTIONS -->
  <div class="hidden md:flex items-center gap-4">
    <button
      (click)="themeService.toggleTheme()"
      class="p-3 rounded-xl bg-gray-100 hover:bg-gray-200 text-gray-700 dark:bg-zinc-850 dark:hover:bg-zinc-800 dark:text-zinc-200 transition duration-300 text-base cursor-pointer border-none"
      aria-label="Toggle Theme"
    >
      @if (themeService.isDark()) {
        <i class="fa-solid fa-sun"></i>
      } @else {
        <i class="fa-solid fa-moon"></i>
      }
    </button>
    <button
      (click)="showForm = true"
      class="bg-red-600 text-white px-6 py-3 rounded-xl hover:bg-red-500 hover:shadow-[0_0_20px_rgba(239,68,68,0.4)] transition duration-300 font-semibold text-sm cursor-pointer border-none"
    >
      Apply Now
    </button>
  </div>

  <!-- MOBILE CONTROLS -->
  <div class="flex md:hidden items-center gap-3">
    <button
      (click)="themeService.toggleTheme()"
      class="p-2.5 rounded-xl bg-gray-100 dark:bg-zinc-855 text-gray-700 dark:text-zinc-250 text-sm cursor-pointer border-none"
      aria-label="Toggle Theme"
    >
      @if (themeService.isDark()) {
        <i class="fa-solid fa-sun"></i>
      } @else {
        <i class="fa-solid fa-moon"></i>
      }
    </button>
    <button
      class="text-2xl text-gray-700 dark:text-white hover:text-red-500 transition cursor-pointer border-none bg-transparent"
      (click)="menuOpen = !menuOpen"
    >
      @if (menuOpen) {
        <i class="fa-solid fa-xmark"></i>
      } @else {
        <i class="fa-solid fa-bars"></i>
      }
    </button>
  </div>

  <!-- MOBILE MENU -->
  <div
    [class]="'absolute top-[80px] left-0 w-full bg-white dark:bg-[#0D0D0E]/95 border-b border-gray-100 dark:border-zinc-800 transition-all duration-300 md:hidden ' + (menuOpen ? 'opacity-100 visible' : 'opacity-0 invisible')"
  >
    <ul class="flex flex-col items-center gap-8 py-10 text-gray-755 dark:text-zinc-300 font-medium">
      <li (click)="menuOpen = false">
        <a routerLink="/" routerLinkActive="text-red-600 dark:text-red-500" [routerLinkActiveOptions]="{exact: true}">Home</a>
      </li>
      <li (click)="menuOpen = false">
        <a routerLink="/about" routerLinkActive="text-red-600 dark:text-red-500">About</a>
      </li>
      <li (click)="menuOpen = false">
        <a routerLink="/courses" routerLinkActive="text-red-600 dark:text-red-500">Courses</a>
      </li>
      <li (click)="menuOpen = false">
        <a routerLink="/Research" routerLinkActive="text-red-600 dark:text-red-500">Research</a>
      </li>
      <li (click)="menuOpen = false">
        <a routerLink="/community" routerLinkActive="text-red-600 dark:text-red-500">Community</a>
      </li>
      <li (click)="menuOpen = false">
        <a routerLink="/contact" routerLinkActive="text-red-600 dark:text-red-500">Contact</a>
      </li>
      @if (authService.isLoggedIn()) {
        <li (click)="menuOpen = false">
          <a routerLink="/dashboard">Dashboard</a>
        </li>
      } @else {
        <li (click)="menuOpen = false">
          <a routerLink="/login">Login</a>
        </li>
      }
      <button
        (click)="showForm = true; menuOpen = false"
        class="bg-red-600 text-white px-6 py-3 rounded-xl hover:bg-red-500 hover:shadow-[0_0_20px_rgba(239,68,68,0.4)] transition duration-300 text-sm font-semibold border-none"
      >
        Apply Now
      </button>
    </ul>
  </div>
</nav>

<!-- APPLICATION FORM MODAL -->
@if (showForm) {
  <div class="fixed inset-0 bg-black/60 dark:bg-black/80 flex justify-center items-center z-50 px-4 backdrop-blur-sm">
    <div class="bg-white dark:bg-[#141416] border border-gray-200 dark:border-zinc-800/80 text-gray-800 dark:text-white w-full max-w-2xl rounded-3xl p-6 md:p-10 relative overflow-y-auto max-h-[90vh] shadow-2xl">
      <!-- CLOSE BUTTON -->
      <button
        (click)="showForm = false"
        class="absolute top-5 right-5 text-2xl text-gray-400 hover:text-gray-600 dark:text-zinc-400 dark:hover:text-white transition cursor-pointer border-none bg-transparent"
      >
        ✕
      </button>

      <!-- TITLE -->
      <h1 class="text-3xl md:text-4xl font-bold mb-2 text-gray-955 dark:text-white">Apply Now</h1>
      <p class="text-gray-500 dark:text-zinc-400 mb-8">Fill the application form to join Divijix Academy.</p>

      <!-- FORM -->
      <form [formGroup]="applyForm" (ngSubmit)="handleSubmit()" class="space-y-6">
        <!-- NAME -->
        <div class="text-left">
          <label class="block mb-2 font-medium text-sm text-gray-700 dark:text-zinc-300">Full Name *</label>
          <input
            type="text"
            formControlName="name"
            placeholder="Enter your full name"
            class="w-full bg-white dark:bg-[#0D0D0E] border border-gray-300 dark:border-zinc-800 rounded-xl px-5 py-4 outline-none focus:border-red-500 focus:ring-1 focus:ring-red-500 text-sm text-gray-855 dark:text-white placeholder-gray-400 dark:placeholder-zinc-500"
          />
          @if (applyForm.get('name')?.touched && applyForm.get('name')?.errors?.['required']) {
            <p class="text-red-500 text-xs mt-1">Full Name is required.</p>
          }
        </div>

        <!-- EMAIL -->
        <div class="text-left">
          <label class="block mb-2 font-medium text-sm text-gray-700 dark:text-zinc-300">Email *</label>
          <input
            type="email"
            formControlName="email"
            placeholder="Enter your email"
            class="w-full bg-white dark:bg-[#0D0D0E] border border-gray-300 dark:border-zinc-800 rounded-xl px-5 py-4 outline-none focus:border-red-500 focus:ring-1 focus:ring-red-500 text-sm text-gray-855 dark:text-white placeholder-gray-400 dark:placeholder-zinc-500"
          />
          @if (applyForm.get('email')?.touched && applyForm.get('email')?.errors) {
            <p class="text-red-500 text-xs mt-1">
              @if (applyForm.get('email')?.errors?.['required']) {
                Email address is required.
              } @else if (applyForm.get('email')?.errors?.['email']) {
                Please enter a valid email address.
              }
            </p>
          }
        </div>

        <!-- PHONE -->
        <div class="text-left">
          <label class="block mb-2 font-medium text-sm text-gray-700 dark:text-zinc-300">Phone Number *</label>
          <input
            type="text"
            formControlName="phone"
            placeholder="9876543210"
            class="w-full bg-white dark:bg-[#0D0D0E] border border-gray-300 dark:border-zinc-800 rounded-xl px-5 py-4 outline-none focus:border-red-500 focus:ring-1 focus:ring-red-500 text-sm text-gray-855 dark:text-white placeholder-gray-400 dark:placeholder-zinc-500"
          />
          @if (applyForm.get('phone')?.touched && applyForm.get('phone')?.errors) {
            <p class="text-red-500 text-xs mt-1">
              @if (applyForm.get('phone')?.errors?.['required']) {
                Phone number is required.
              } @else if (applyForm.get('phone')?.errors?.['pattern']) {
                Please enter a valid 10-digit phone number.
              }
            </p>
          }
        </div>

        <!-- LINKEDIN -->
        <div class="text-left">
          <label class="block mb-2 font-medium text-sm text-gray-700 dark:text-zinc-300">LinkedIn Profile *</label>
          <input
            type="url"
            formControlName="linkedin"
            placeholder="https://linkedin.com/in/username"
            class="w-full bg-white dark:bg-[#0D0D0E] border border-gray-300 dark:border-zinc-800 rounded-xl px-5 py-4 outline-none focus:border-red-500 focus:ring-1 focus:ring-red-550 text-sm text-gray-855 dark:text-white placeholder-gray-400 dark:placeholder-zinc-500"
          />
          @if (applyForm.get('linkedin')?.touched && applyForm.get('linkedin')?.errors) {
            <p class="text-red-500 text-xs mt-1">
              @if (applyForm.get('linkedin')?.errors?.['required']) {
                LinkedIn profile link is required.
              } @else if (applyForm.get('linkedin')?.errors?.['pattern']) {
                Please enter a valid LinkedIn profile URL.
              }
            </p>
          }
        </div>

        <!-- COLLEGE -->
        <div class="text-left">
          <label class="block mb-2 font-medium text-sm text-gray-700 dark:text-zinc-300">College Name *</label>
          <input
            type="text"
            formControlName="college"
            placeholder="Enter your college name"
            class="w-full bg-white dark:bg-[#0D0D0E] border border-gray-300 dark:border-zinc-800 rounded-xl px-5 py-4 outline-none focus:border-red-500 focus:ring-1 focus:ring-red-555 text-sm text-gray-855 dark:text-white placeholder-gray-400 dark:placeholder-zinc-500"
          />
          @if (applyForm.get('college')?.touched && applyForm.get('college')?.errors?.['required']) {
            <p class="text-red-500 text-xs mt-1">College Name is required.</p>
          }
        </div>

        <!-- PASSOUT YEAR -->
        <div class="text-left">
          <label class="block mb-2 font-medium text-sm text-gray-700 dark:text-zinc-300">Passout Year *</label>
          <input
            type="text"
            formControlName="passout"
            placeholder="2026"
            class="w-full bg-white dark:bg-[#0D0D0E] border border-gray-300 dark:border-zinc-800 rounded-xl px-5 py-4 outline-none focus:border-red-500 focus:ring-1 focus:ring-red-555 text-sm text-gray-855 dark:text-white placeholder-gray-400 dark:placeholder-zinc-500"
          />
          @if (applyForm.get('passout')?.touched && applyForm.get('passout')?.errors) {
            <p class="text-red-500 text-xs mt-1">
              @if (applyForm.get('passout')?.errors?.['required']) {
                Passout Year is required.
              } @else if (applyForm.get('passout')?.errors?.['pattern']) {
                Please enter a valid 4-digit year.
              }
            </p>
          }
        </div>

        <!-- SUBMIT BUTTON -->
        <button
          type="submit"
          [disabled]="submitting"
          class="w-full bg-red-600 text-white py-4 rounded-xl hover:bg-red-500 hover:shadow-[0_0_20px_rgba(239,68,68,0.4)] transition duration-300 font-semibold text-sm shadow-sm cursor-pointer border-none"
        >
          {{submitting ? 'Submitting Application...' : 'Submit Application'}}
        </button>
      </form>
    </div>
  </div>
}
