// src/components/Programs.jsx
import React, { useState, useEffect } from "react";
import { FaRobot, FaBrain, FaCode, FaDatabase, FaSearch } from "react-icons/fa";

function Programs() {
  const [courses, setCourses] = useState([]);
  const [loading, setLoading] = useState(true);

  const iconMap = {
    FaCode: <FaCode />,
    FaBrain: <FaBrain />,
    FaRobot: <FaRobot />,
    FaSearch: <FaSearch />,
    FaDatabase: <FaDatabase />
  };

  useEffect(() => {
    const fetchCourses = async () => {
      try {
        const response = await fetch("/api/courses");
        if (response.ok) {
          const data = await response.json();
          setCourses(data);
        }
      } catch (err) {
        console.error("Error fetching homepage courses:", err);
      } finally {
        setLoading(false);
      }
    };
    fetchCourses();
  }, []);

  return (
    <section className="px-5 md:px-10 py-20 md:py-24 bg-[#f8f8f8] overflow-hidden">
      {/* TITLE */}
      <div className="text-center mb-16">
        <p className="text-red-500 font-semibold mb-3 text-sm md:text-base">
          OUR PROGRAMS
        </p>
        <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold leading-tight">
          Cutting Edge AI & Foundation Courses
        </h1>
      </div>

      {/* CARDS */}
      {loading ? (
        <div className="flex justify-center items-center py-20">
          <div className="animate-spin rounded-full h-10 w-10 border-t-2 border-b-2 border-red-600"></div>
        </div>
      ) : courses.length === 0 ? (
        <div className="text-center text-gray-500 py-10">No programs available at the moment.</div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8">
          {courses.map((course, index) => (
            <div
              key={course.id || index}
              className="bg-white p-6 md:p-8 rounded-3xl hover:shadow-2xl transition duration-300 hover:-translate-y-2 flex flex-col justify-between"
            >
              <div>
                {/* ICON */}
                <div className="text-4xl md:text-5xl text-red-600 mb-6">
                  {course.is_technical ? (
                    iconMap[course.icon_name] || <FaCode />
                  ) : (
                    <FaBrain />
                  )}
                </div>

                {/* LEVEL */}
                <span className="text-[10px] bg-slate-100 px-2.5 py-1 rounded-lg text-slate-500 font-bold uppercase tracking-wider mb-3 inline-block">
                  {course.level}
                </span>

                {/* TITLE */}
                <h1 className="text-xl md:text-2xl font-bold mb-4 leading-snug text-gray-900">
                  {course.title}
                </h1>

                {/* DESCRIPTION */}
                <p className="text-gray-600 leading-7 text-sm md:text-base line-clamp-4">
                  {course.description}
                </p>
              </div>
            </div>
          ))}
        </div>
      )}
    </section>
  );
}

export default Programs;

// src/app/components/programs/programs.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { ApiService } from '../../services/api.service';

interface Course {
  id?: number;
  title: string;
  description: string;
  level: string;
  is_technical: boolean;
  icon_name: string;
}

@Component({
  selector: 'app-programs',
  standalone: true,
  templateUrl: './programs.component.html'
})
export class ProgramsComponent implements OnInit {
  private apiService = inject(ApiService);

  courses: Course[] = [];
  loading = true;

  ngOnInit() {
    this.apiService.get<Course[]>('/api/courses').subscribe({
      next: (data) => {
        this.courses = data;
        this.loading = false;
      },
      error: (err) => {
        console.error('Error fetching homepage courses:', err);
        this.loading = false;
      }
    });
  }

  getIconClass(course: Course): string {
    if (!course.is_technical) {
      return 'fa-solid fa-brain';
    }
    const mappings: Record<string, string> = {
      'FaCode': 'fa-solid fa-code',
      'FaBrain': 'fa-solid fa-brain',
      'FaRobot': 'fa-solid fa-robot',
      'FaSearch': 'fa-solid fa-magnifying-glass',
      'FaDatabase': 'fa-solid fa-database'
    };
    return mappings[course.icon_name] || 'fa-solid fa-code';
  }
}

<section class="relative px-6 md:px-16 py-24 bg-white dark:bg-[#0A0A0B] overflow-hidden text-gray-800 dark:text-white transition-colors duration-250">
  
  <!-- Subtle Gradient Background -->
  <div class="absolute top-1/3 left-1/2 -translate-x-1/2 w-[500px] h-[500px] rounded-full bg-red-650/[0.03] dark:bg-red-500/[0.01] blur-[120px] pointer-events-none"></div>

  <!-- TITLE -->
  <div class="text-center mb-16 space-y-4">
    <p class="text-red-655 dark:text-red-500 font-extrabold text-xs md:text-sm tracking-widest uppercase">
      Our Programs
    </p>
    <h2 class="text-3xl md:text-4xl lg:text-5xl font-black tracking-tight text-gray-955 dark:text-white">
      Cutting-Edge AI & Foundation Courses
    </h2>
    <div class="w-12 h-1 bg-red-600 dark:bg-red-500 mx-auto rounded-full"></div>
  </div>

  <!-- CARDS -->
  <div class="max-w-7xl mx-auto">
    @if (loading) {
      <div class="flex justify-center items-center py-20">
        <div class="animate-spin rounded-full h-10 w-10 border-t-2 border-b-2 border-red-600 dark:border-red-500"></div>
      </div>
    } @else if (courses.length === 0) {
      <div class="text-center text-gray-555 dark:text-zinc-500 py-10">No programs available at the moment.</div>
    } @else {
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
        @for (course of courses; track course.id || $index) {
          <div class="group relative bg-[#f9fafb] dark:bg-[#111112] border border-gray-200/60 dark:border-zinc-800/80 p-8 rounded-[2rem] hover:border-red-500/30 dark:hover:border-red-500/20 hover:shadow-[0_20px_50px_rgba(239,68,68,0.05)] hover:-translate-y-1.5 transition-all duration-300 flex flex-col justify-between overflow-hidden">
            
            <!-- Hover Glow Border -->
            <div class="absolute -inset-px rounded-[2rem] bg-gradient-to-tr from-red-600 to-rose-500 opacity-0 group-hover:opacity-10 transition-opacity duration-300 pointer-events-none"></div>

            <div>
              <!-- ICON & LEVEL -->
              <div class="flex items-center justify-between mb-8">
                <div class="inline-flex items-center justify-center w-14 h-14 rounded-2xl bg-red-50 dark:bg-red-950/20 text-red-600 dark:text-red-500 group-hover:scale-105 group-hover:bg-red-600 group-hover:text-white transition-all duration-300 text-3xl">
                  <i [class]="getIconClass(course)"></i>
                </div>
                <span class="text-[10px] bg-red-50 dark:bg-red-950/20 border border-red-200/30 dark:border-red-900/30 px-3 py-1 rounded-full text-red-655 dark:text-red-400 font-extrabold uppercase tracking-wider">
                  {{course.level}}
                </span>
              </div>

              <!-- TITLE -->
              <h3 class="text-xl md:text-2xl font-bold mb-4 leading-snug text-gray-955 dark:text-white group-hover:text-red-600 dark:group-hover:text-red-500 transition-colors duration-250">
                {{course.title}}
              </h3>

              <!-- DESCRIPTION -->
              <p class="text-gray-600 dark:text-zinc-400 leading-relaxed text-sm md:text-base line-clamp-3 mb-6">
                {{course.description}}
              </p>
            </div>

            <!-- ACTION LINK -->
            <div class="pt-4 border-t border-gray-200/40 dark:border-zinc-800/50 flex items-center justify-between text-xs font-bold text-gray-950 dark:text-white">
              <span>View Details</span>
              <span class="w-8 h-8 rounded-full bg-white dark:bg-zinc-800 border border-gray-200 dark:border-zinc-700 flex items-center justify-center text-red-600 dark:text-red-500 group-hover:translate-x-1 group-hover:bg-red-600 group-hover:text-white group-hover:border-red-600 transition-all duration-300">
                <i class="fa-solid fa-arrow-right"></i>
              </span>
            </div>
          </div>
        }
      </div>
    }
  </div>
</section>
