// src/app/pages/about/about.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NavbarComponent } from '../../components/navbar/navbar.component';
import { FooterComponent } from '../../components/footer/footer.component';

@Component({
  selector: 'app-about',
  standalone: true,
  imports: [NavbarComponent, FooterComponent, RouterLink],
  templateUrl: './about.component.html'
})
export class AboutComponent {}

<div class="overflow-hidden bg-[#f8f8f8] dark:bg-[#080809] text-gray-800 dark:text-white transition-colors duration-250">
  <app-navbar />

  <!-- HERO SECTION -->
  <section class="grid grid-cols-1 md:grid-cols-2 items-center gap-12 md:gap-16 px-5 md:px-10 py-16 md:py-24 bg-[#f8f8f8] dark:bg-[#080809] transition-colors duration-250">
    <!-- LEFT -->
    <div>
      <p class="text-red-500 dark:text-red-500 font-semibold mb-4 text-sm md:text-base tracking-wider uppercase">
        ABOUT Divijix academy
      </p>
      <h1 class="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold leading-tight text-gray-955 dark:text-white">
        Building Future AI Innovators
      </h1>
      <p class="text-gray-605 dark:text-zinc-450 mt-6 text-base md:text-lg leading-7 md:leading-8">
        Divijix academy is a next-generation AI learning platform focused on
        Artificial Intelligence, Machine Learning, Data Science,
        Full Stack AI Development, and Cloud Computing.
      </p>
      <p class="text-gray-605 dark:text-zinc-450 mt-4 text-base md:text-lg leading-7 md:leading-8">
        We help students become industry-ready through real-world
        projects, expert mentorship, and advanced AI training.
      </p>

      <!-- BUTTONS -->
      <div class="flex flex-wrap gap-5 mt-10">
        <button routerLink="/courses" class="bg-red-600 text-white px-6 md:px-7 py-3 rounded-xl hover:bg-red-700 transition duration-300 border-none cursor-pointer">
          Explore Courses
        </button>
        <button routerLink="/contact" class="border border-black dark:border-white px-6 md:px-7 py-3 rounded-xl hover:bg-black hover:text-white dark:hover:bg-white dark:hover:text-black transition duration-300 bg-transparent text-black dark:text-white cursor-pointer">
          Contact Us
        </button>
      </div>
    </div>

    <!-- RIGHT IMAGE -->
    <div class="flex justify-center">
      <img
        src="assets/about.jpg"
        alt="About Kingu"
        class="w-full max-w-[550px] h-[300px] md:h-[500px] object-cover rounded-3xl shadow-2xl border border-gray-200 dark:border-zinc-800"
      />
    </div>
  </section>

  <!-- STATS SECTION -->
  <section class="px-5 md:px-10 py-20 bg-white dark:bg-[#0D0D0E] border-y border-gray-150 dark:border-zinc-900 transition-colors duration-250">
    <div class="text-center mb-16">
      <p class="text-red-550 font-semibold mb-3 tracking-wider uppercase">
        OUR IMPACT
      </p>
      <h1 class="text-3xl md:text-5xl font-bold text-gray-955 dark:text-white">
        Transforming Careers with AI
      </h1>
    </div>

    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">
      <div class="bg-[#f8f8f8] dark:bg-[#141416] border border-gray-200 dark:border-zinc-800/80 p-10 rounded-3xl shadow">
        <h1 class="text-5xl font-bold text-red-600 dark:text-red-500">
          500+
        </h1>
        <p class="mt-4 text-gray-600 dark:text-zinc-400 text-lg">
          Students Trained
        </p>
      </div>

      <div class="bg-[#f8f8f8] dark:bg-[#141416] border border-gray-200 dark:border-zinc-800/80 p-10 rounded-3xl shadow">
        <h1 class="text-5xl font-bold text-red-600 dark:text-red-500">
          15+
        </h1>
        <p class="mt-4 text-gray-600 dark:text-zinc-400 text-lg">
          AI Programs
        </p>
      </div>

      <div class="bg-[#f8f8f8] dark:bg-[#141416] border border-gray-200 dark:border-zinc-800/80 p-10 rounded-3xl shadow">
        <h1 class="text-5xl font-bold text-red-600 dark:text-red-500">
          95%
        </h1>
        <p class="mt-4 text-gray-600 dark:text-zinc-400 text-lg">
          Career Success
        </p>
      </div>

      <div class="bg-[#f8f8f8] dark:bg-[#141416] border border-gray-200 dark:border-zinc-800/80 p-10 rounded-3xl shadow">
        <h1 class="text-5xl font-bold text-red-600 dark:text-red-500">
          100%
        </h1>
        <p class="mt-4 text-gray-600 dark:text-zinc-400 text-lg">
          Practical Learning
        </p>
      </div>
    </div>
  </section>

  <!-- MISSION SECTION -->
  <section class="px-5 md:px-10 py-20 bg-[#f8f8f8] dark:bg-[#080809] border-b border-gray-150 dark:border-zinc-900 transition-colors duration-250">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-10">
      <!-- MISSION -->
      <div class="bg-white dark:bg-[#141416] border border-gray-200 dark:border-zinc-800/80 p-10 rounded-3xl shadow">
        <h1 class="text-3xl font-bold mb-6 text-gray-955 dark:text-white">
          Our Mission
        </h1>
        <p class="text-gray-655 dark:text-zinc-400 leading-8 text-base md:text-lg">
          To make high-quality AI education accessible to every student
          and prepare them for the future of technology through
          practical learning.
        </p>
      </div>

      <!-- VISION -->
      <div class="bg-white dark:bg-[#141416] border border-gray-200 dark:border-zinc-800/80 p-10 rounded-3xl shadow">
        <h1 class="text-3xl font-bold mb-6 text-gray-955 dark:text-white">
          Our Vision
        </h1>
        <p class="text-gray-655 dark:text-zinc-400 leading-8 text-base md:text-lg">
          To become India’s leading AI innovation and training institute
          by empowering students with next-generation skills.
        </p>
      </div>
    </div>
  </section>

  <!-- TEAM SECTION -->
  <section class="px-5 md:px-10 py-20 bg-white dark:bg-[#0D0D0E] transition-colors duration-250">
    <div class="text-center mb-16">
      <p class="text-red-550 font-semibold mb-3 tracking-wider uppercase">
        OUR TEAM
      </p>
      <h1 class="text-3xl md:text-5xl font-bold text-gray-955 dark:text-white">
        Meet Our Mentors
      </h1>
    </div>

    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">
      <div class="bg-[#f8f8f8] dark:bg-[#141416] border border-gray-200 dark:border-zinc-800/80 p-8 rounded-3xl text-center shadow">
        <div class="h-[220px] md:h-[250px] bg-gray-200 dark:bg-zinc-800 rounded-2xl mb-6"></div>
        <h1 class="text-2xl font-bold text-gray-955 dark:text-white">
          Rahul Sharma
        </h1>
        <p class="text-red-500 mt-2 font-medium">
          AI Engineer
        </p>
      </div>

      <div class="bg-[#f8f8f8] dark:bg-[#141416] border border-gray-200 dark:border-zinc-800/80 p-8 rounded-3xl text-center shadow">
        <div class="h-[220px] md:h-[250px] bg-gray-200 dark:bg-zinc-800 rounded-2xl mb-6"></div>
        <h1 class="text-2xl font-bold text-gray-955 dark:text-white">
          Priya Patel
        </h1>
        <p class="text-red-500 mt-2 font-medium">
          ML Expert
        </p>
      </div>

      <div class="bg-[#f8f8f8] dark:bg-[#141416] border border-gray-200 dark:border-zinc-800/80 p-8 rounded-3xl text-center shadow">
        <div class="h-[220px] md:h-[250px] bg-gray-200 dark:bg-zinc-800 rounded-2xl mb-6"></div>
        <h1 class="text-2xl font-bold text-gray-955 dark:text-white">
          Arjun Verma
        </h1>
        <p class="text-red-500 mt-2 font-medium">
          Data Scientist
        </p>
      </div>

      <div class="bg-[#f8f8f8] dark:bg-[#141416] border border-gray-200 dark:border-zinc-800/80 p-8 rounded-3xl text-center shadow">
        <div class="h-[220px] md:h-[250px] bg-gray-200 dark:bg-zinc-800 rounded-2xl mb-6"></div>
        <h1 class="text-2xl font-bold text-gray-955 dark:text-white">
          Sneha Iyer
        </h1>
        <p class="text-red-550 mt-2 font-medium">
          Cloud Architect
        </p>
      </div>
    </div>
  </section>

  <app-footer />
</div>

// src/pages/About.jsx
import React from "react";

import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

import img from "../assets/about.jpg";

function About() {

  return (

    <div className="overflow-hidden">

      <Navbar />

      {/* HERO SECTION */}

      <section className="grid grid-cols-1 md:grid-cols-2 items-center gap-12 md:gap-16 px-5 md:px-10 py-16 md:py-24 bg-[#f8f8f8]">

        {/* LEFT */}

        <div>

          <p className="text-red-500 font-semibold mb-4 text-sm md:text-base">

            ABOUT Divijix academy

          </p>

          <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold leading-tight">

            Building Future AI Innovators

          </h1>

          <p className="text-gray-600 mt-6 text-base md:text-lg leading-7 md:leading-8">

            Divijix academy is a next-generation AI learning platform focused on
            Artificial Intelligence, Machine Learning, Data Science,
            Full Stack AI Development, and Cloud Computing.

          </p>

          <p className="text-gray-600 mt-4 text-base md:text-lg leading-7 md:leading-8">

            We help students become industry-ready through real-world
            projects, expert mentorship, and advanced AI training.

          </p>

          {/* BUTTONS */}

          <div className="flex flex-wrap gap-5 mt-10">

            <button className="bg-red-600 text-white px-6 md:px-7 py-3 rounded-xl hover:bg-red-700 transition duration-300">

              Explore Courses

            </button>

            <button className="border border-black px-6 md:px-7 py-3 rounded-xl hover:bg-black hover:text-white transition duration-300">

              Contact Us

            </button>

          </div>

        </div>

        {/* RIGHT IMAGE */}

        <div className="flex justify-center">

          <img
            src={img}
            alt="About Kingu"
            className="w-full max-w-[550px] h-[300px] md:h-[500px] object-cover rounded-3xl shadow-2xl"
          />

        </div>

      </section>

      {/* STATS SECTION */}

      <section className="px-5 md:px-10 py-20 bg-white">

        <div className="text-center mb-16">

          <p className="text-red-500 font-semibold mb-3">

            OUR IMPACT

          </p>

          <h1 className="text-3xl md:text-5xl font-bold">

            Transforming Careers with AI

          </h1>

        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">

          <div className="bg-[#f8f8f8] p-10 rounded-3xl shadow">

            <h1 className="text-5xl font-bold text-red-600">

              500+

            </h1>

            <p className="mt-4 text-gray-600 text-lg">

              Students Trained

            </p>

          </div>

          <div className="bg-[#f8f8f8] p-10 rounded-3xl shadow">

            <h1 className="text-5xl font-bold text-red-600">

              15+

            </h1>

            <p className="mt-4 text-gray-600 text-lg">

              AI Programs

            </p>

          </div>

          <div className="bg-[#f8f8f8] p-10 rounded-3xl shadow">

            <h1 className="text-5xl font-bold text-red-600">

              95%

            </h1>

            <p className="mt-4 text-gray-600 text-lg">

              Career Success

            </p>

          </div>

          <div className="bg-[#f8f8f8] p-10 rounded-3xl shadow">

            <h1 className="text-5xl font-bold text-red-600">

              100%

            </h1>

            <p className="mt-4 text-gray-600 text-lg">

              Practical Learning

            </p>

          </div>

        </div>

      </section>

      {/* MISSION SECTION */}

      <section className="px-5 md:px-10 py-20 bg-[#f8f8f8]">

        <div className="grid grid-cols-1 md:grid-cols-2 gap-10">

          {/* MISSION */}

          <div className="bg-white p-10 rounded-3xl shadow">

            <h1 className="text-3xl font-bold mb-6">

              Our Mission

            </h1>

            <p className="text-gray-600 leading-8 text-base md:text-lg">

              To make high-quality AI education accessible to every student
              and prepare them for the future of technology through
              practical learning.

            </p>

          </div>

          {/* VISION */}

          <div className="bg-white p-10 rounded-3xl shadow">

            <h1 className="text-3xl font-bold mb-6">

              Our Vision

            </h1>

            <p className="text-gray-600 leading-8 text-base md:text-lg">

              To become India’s leading AI innovation and training institute
              by empowering students with next-generation skills.

            </p>

          </div>

        </div>

      </section>

      {/* TEAM SECTION */}

      <section className="px-5 md:px-10 py-20 bg-white">

        <div className="text-center mb-16">

          <p className="text-red-500 font-semibold mb-3">

            OUR TEAM

          </p>

          <h1 className="text-3xl md:text-5xl font-bold">

            Meet Our Mentors

          </h1>

        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">

          <div className="bg-[#f8f8f8] p-8 rounded-3xl text-center shadow">

            <div className="h-[220px] md:h-[250px] bg-gray-200 rounded-2xl mb-6"></div>

            <h1 className="text-2xl font-bold">

              Rahul Sharma

            </h1>

            <p className="text-red-500 mt-2">

              AI Engineer

            </p>

          </div>

          <div className="bg-[#f8f8f8] p-8 rounded-3xl text-center shadow">

            <div className="h-[220px] md:h-[250px] bg-gray-200 rounded-2xl mb-6"></div>

            <h1 className="text-2xl font-bold">

              Priya Patel

            </h1>

            <p className="text-red-500 mt-2">

              ML Expert

            </p>

          </div>

          <div className="bg-[#f8f8f8] p-8 rounded-3xl text-center shadow">

            <div className="h-[220px] md:h-[250px] bg-gray-200 rounded-2xl mb-6"></div>

            <h1 className="text-2xl font-bold">

              Arjun Verma

            </h1>

            <p className="text-red-500 mt-2">

              Data Scientist

            </p>

          </div>

          <div className="bg-[#f8f8f8] p-8 rounded-3xl text-center shadow">

            <div className="h-[220px] md:h-[250px] bg-gray-200 rounded-2xl mb-6"></div>

            <h1 className="text-2xl font-bold">

              Sneha Iyer

            </h1>

            <p className="text-red-500 mt-2">

              Cloud Architect

            </p>

          </div>

        </div>

      </section>

      <Footer />

    </div>

  );
}

export default About;
