// src/app/pages/contact/contact.component.ts
import { Component, inject } from '@angular/core';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { NavbarComponent } from '../../components/navbar/navbar.component';
import { FooterComponent } from '../../components/footer/footer.component';
import { ApiService } from '../../services/api.service';

interface ContactInfo {
  iconClass: string;
  title: string;
  value: string;
  subtitle: string;
}

@Component({
  selector: 'app-contact',
  standalone: true,
  imports: [NavbarComponent, FooterComponent, ReactiveFormsModule, CommonModule],
  templateUrl: './contact.component.html'
})
export class ContactComponent {
  private apiService = inject(ApiService);
  private fb = inject(FormBuilder);

  contactInfo: ContactInfo[] = [
    {
      iconClass: 'fa-brands fa-whatsapp',
      title: 'WhatsApp',
      value: '8009799550',
      subtitle: 'Instant messaging'
    },
    {
      iconClass: 'fa-solid fa-envelope',
      title: 'Email',
      value: 'divijixtechnology@zohomail.in',
      subtitle: 'Response within 24hrs'
    },
    {
      iconClass: 'fa-brands fa-instagram',
      title: 'Instagram',
      value: '@kingu_ai',
      subtitle: 'Follow us for updates'
    }
  ];

  contactForm: FormGroup = this.fb.group({
    name: ['', Validators.required],
    phone: ['', [Validators.required, Validators.pattern('^[0-9]{10}$')]],
    email: ['', [Validators.required, Validators.email]],
    subject: ['', Validators.required],
    message: ['', Validators.required]
  });

  loading = false;
  status = { type: '', message: '' };

  handleSubmit() {
    if (this.contactForm.invalid) {
      this.contactForm.markAllAsTouched();
      return;
    }

    this.loading = true;
    this.status = { type: '', message: '' };

    this.apiService.post('/api/contact', this.contactForm.value).subscribe({
      next: () => {
        this.status = { type: 'success', message: 'Message sent successfully!' };
        this.contactForm.reset();
        this.loading = false;
      },
      error: (err) => {
        this.status = { type: 'error', message: err.error?.error || "Failed to submit message" };
        this.loading = false;
      }
    });
  }
}

<div class="bg-[#f5f5f5] dark:bg-[#080809] min-h-screen text-gray-800 dark:text-white transition-colors duration-250 overflow-hidden">
  <app-navbar />

  <!-- HERO -->
  <section class="text-center py-20 md:py-28 px-5 md:px-10">
    <h1 class="text-4xl md:text-5xl lg:text-6xl font-bold mb-8 text-gray-955 dark:text-white">
      Let's Connect
    </h1>
    <p class="text-gray-605 dark:text-zinc-400 text-base md:text-lg leading-7 md:leading-8 max-w-3xl mx-auto">
      Have a question about our programs? Ready to apply? Want to collaborate? We'd love to hear from you.
    </p>
  </section>

  <!-- CONTACT SECTION -->
  <section class="px-5 md:px-10 pb-20 md:pb-28">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-10 md:gap-20">
      <!-- LEFT SIDE -->
      <div>
        <h1 class="text-3xl md:text-4xl lg:text-5xl font-bold mb-12 text-gray-955 dark:text-white">
          Get in Touch
        </h1>

        <!-- CONTACT CARDS -->
        <div class="space-y-8">
          @for (element of contactInfo; track $index) {
            <div class="bg-white dark:bg-[#141416] border border-gray-100 dark:border-zinc-800/80 p-6 md:p-8 rounded-3xl shadow hover:shadow-2xl transition duration-300 flex flex-col sm:flex-row gap-6 items-start">
              <!-- ICON -->
              <div class="w-14 h-14 md:w-16 md:h-16 rounded-2xl bg-black dark:bg-zinc-800 text-white flex items-center justify-center text-xl md:text-2xl shrink-0">
                <i [class]="element.iconClass"></i>
              </div>
              <!-- TEXT -->
              <div>
                <h1 class="text-xl md:text-2xl font-bold mb-2 text-gray-955 dark:text-white">
                  {{element.title}}
                </h1>
                <p class="text-gray-700 dark:text-zinc-305 mb-2 break-all font-medium">
                  {{element.value}}
                </p>
                <p class="text-gray-500 dark:text-zinc-500 text-sm md:text-base">
                  {{element.subtitle}}
                </p>
              </div>
            </div>
          }
        </div>

        <!-- LOCATION -->
        <div class="mt-16">
          <p class="tracking-widest text-gray-500 mb-5 text-sm font-semibold uppercase">
            OUR LOCATION
          </p>
          <p class="text-gray-700 dark:text-zinc-350 leading-7 md:leading-8">
            Jaipur Rajasthan
          </p>
        </div>
      </div>

      <!-- RIGHT SIDE FORM -->
      <div class="bg-white dark:bg-[#141416] border border-gray-100 dark:border-zinc-800/85 p-6 md:p-10 rounded-3xl shadow">
        <h1 class="text-3xl md:text-4xl font-bold mb-4 text-gray-955 dark:text-white">
          Send a Message
        </h1>
        <p class="text-gray-500 dark:text-zinc-400 mb-10">
          We'll get back to you as soon as possible.
        </p>

        @if (status.message) {
          <div
            [ngClass]="{
              'bg-green-50 text-green-600 border-green-200': status.type === 'success',
              'bg-red-50 text-red-600 border-red-200': status.type === 'error'
            }"
            class="p-4 rounded-2xl mb-6 text-center text-sm font-semibold border"
          >
            {{status.message}}
          </div>
        }

        <!-- FORM -->
        <form [formGroup]="contactForm" (ngSubmit)="handleSubmit()" class="space-y-8">
          <!-- ROW 1 -->
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div class="text-left">
              <label class="block mb-3 font-medium text-sm text-gray-700 dark:text-zinc-300">
                Full Name *
              </label>
              <input
                type="text"
                formControlName="name"
                placeholder="John Doe"
                class="w-full bg-white dark:bg-[#0D0D0E] border border-gray-300 dark:border-zinc-800 rounded-xl px-5 py-4 outline-none focus:border-red-655 focus:ring-1 focus:ring-red-500 text-sm text-gray-855 dark:text-white placeholder-gray-400 dark:placeholder-zinc-500"
              />
              @if (contactForm.get('name')?.touched && contactForm.get('name')?.errors?.['required']) {
                <p class="text-red-500 text-xs mt-1">Full Name is required.</p>
              }
            </div>
            <div class="text-left">
              <label class="block mb-3 font-medium text-sm text-gray-700 dark:text-zinc-300">
                Phone *
              </label>
              <input
                type="text"
                formControlName="phone"
                placeholder="9876543210"
                class="w-full bg-white dark:bg-[#0D0D0E] border border-gray-300 dark:border-zinc-800 rounded-xl px-5 py-4 outline-none focus:border-red-655 focus:ring-1 focus:ring-red-500 text-sm text-gray-855 dark:text-white placeholder-gray-400 dark:placeholder-zinc-500"
              />
              @if (contactForm.get('phone')?.touched && contactForm.get('phone')?.errors) {
                <p class="text-red-500 text-xs mt-1">
                  @if (contactForm.get('phone')?.errors?.['required']) {
                    Phone number is required.
                  } @else if (contactForm.get('phone')?.errors?.['pattern']) {
                    Please enter a valid 10-digit phone number.
                  }
                </p>
              }
            </div>
          </div>

          <!-- ROW 2 -->
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div class="text-left">
              <label class="block mb-3 font-medium text-sm text-gray-700 dark:text-zinc-300">
                Email *
              </label>
              <input
                type="email"
                formControlName="email"
                placeholder="john@example.com"
                class="w-full bg-white dark:bg-[#0D0D0E] border border-gray-300 dark:border-zinc-800 rounded-xl px-5 py-4 outline-none focus:border-red-655 focus:ring-1 focus:ring-red-500 text-sm text-gray-855 dark:text-white placeholder-gray-400 dark:placeholder-zinc-500"
              />
              @if (contactForm.get('email')?.touched && contactForm.get('email')?.errors) {
                <p class="text-red-500 text-xs mt-1">
                  @if (contactForm.get('email')?.errors?.['required']) {
                    Email address is required.
                  } @else if (contactForm.get('email')?.errors?.['email']) {
                    Please enter a valid email address.
                  }
                </p>
              }
            </div>
            <div class="text-left">
              <label class="block mb-3 font-medium text-sm text-gray-700 dark:text-zinc-300">
                Subject *
              </label>
              <input
                type="text"
                formControlName="subject"
                placeholder="General Inquiry"
                class="w-full bg-white dark:bg-[#0D0D0E] border border-gray-300 dark:border-zinc-800 rounded-xl px-5 py-4 outline-none focus:border-red-655 focus:ring-1 focus:ring-red-500 text-sm text-gray-855 dark:text-white placeholder-gray-400 dark:placeholder-zinc-500"
              />
              @if (contactForm.get('subject')?.touched && contactForm.get('subject')?.errors?.['required']) {
                <p class="text-red-500 text-xs mt-1">Subject is required.</p>
              }
            </div>
          </div>

          <!-- MESSAGE -->
          <div class="text-left">
            <label class="block mb-3 font-medium text-sm text-gray-700 dark:text-zinc-300">
              Message *
            </label>
            <textarea
              rows="6"
              formControlName="message"
              placeholder="How can we help you?"
              class="w-full bg-white dark:bg-[#0D0D0E] border border-gray-300 dark:border-zinc-800 rounded-xl px-5 py-4 outline-none resize-none focus:border-red-655 focus:ring-1 focus:ring-red-500 text-sm text-gray-855 dark:text-white placeholder-gray-400 dark:placeholder-zinc-500"
            ></textarea>
            @if (contactForm.get('message')?.touched && contactForm.get('message')?.errors?.['required']) {
              <p class="text-red-500 text-xs mt-1">Message is required.</p>
            }
          </div>

          <!-- BUTTON -->
          <button
            type="submit"
            [disabled]="loading"
            class="w-full bg-black text-white dark:bg-white dark:text-black py-4 md:py-5 rounded-xl hover:bg-gray-800 dark:hover:bg-zinc-200 transition font-bold tracking-widest border-none cursor-pointer disabled:opacity-50"
          >
            {{loading ? 'SENDING...' : 'SEND MESSAGE'}}
          </button>
        </form>
      </div>
    </div>
  </section>

  <!-- CTA SECTION -->
  <section class="bg-black text-white text-center py-20 md:py-28 px-5 md:px-10">
    <h1 class="text-3xl md:text-4xl lg:text-5xl font-bold mb-8">
      Book a Free Counseling Session
    </h1>
    <p class="text-gray-450 text-base md:text-lg leading-7 md:leading-8 max-w-2xl mx-auto">
      30-minute session with our admissions advisor to discuss your career path in AI.
    </p>
    <button class="mt-10 bg-white text-black px-6 md:px-10 py-3 md:py-4 rounded-xl font-semibold hover:bg-gray-200 transition border-none cursor-pointer">
      BOOK NOW
    </button>
  </section>

  <!-- MAP SECTION -->
  <section class="px-5 md:px-10 py-20 md:py-28 bg-[#f5f5f5] dark:bg-[#080809] border-t border-gray-150 dark:border-zinc-900 transition-colors duration-250">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-10 md:gap-20 items-center">
      <!-- LEFT -->
      <div>
        <h1 class="text-3xl md:text-4xl lg:text-5xl font-bold mb-10 text-gray-955 dark:text-white">
          Find Us
        </h1>
        <p class="text-gray-700 dark:text-zinc-300 leading-7 md:leading-8 mb-10">
          Divijix academy <br />
          Jaipur, Rajasthan
        </p>
        <div class="space-y-5">
          <div class="flex items-center gap-4">
            <i class="fa-solid fa-map-location-dot text-red-500 text-xl"></i>
            <p class="font-medium">8009799550</p>
          </div>
          <div class="flex items-center gap-4">
            <i class="fa-solid fa-phone text-red-500 text-xl"></i>
            <p class="font-medium">8009799550</p>
          </div>
        </div>
      </div>

      <!-- RIGHT MAP placeholder matching React style -->
      <div class="bg-gray-300 dark:bg-zinc-800 h-[250px] md:h-[400px] rounded-3xl shadow-xl flex items-center justify-center">
        <i class="fa-solid fa-map-marked-alt text-gray-400 dark:text-zinc-600 text-6xl"></i>
      </div>
    </div>
  </section>

  <app-footer />
</div>

// src/pages/Contact.jsx
import React, { useState } from "react";

import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

import {
  FaWhatsapp,
  FaEnvelope,
  FaInstagram,
  FaMapMarkerAlt,
  FaPhoneAlt
} from "react-icons/fa";

function Contact() {

  /* CONTACT JSON DATA */

  const contactInfo = [

    {
      icon: <FaWhatsapp />,
      title: "WhatsApp",
      value: "8009799550",
      subtitle: "Instant messaging"
    },

    {
      icon: <FaEnvelope />,
      title: "Email",
      value: "divijixtechnology@zohomail.in",
      subtitle: "Response within 24hrs"
    },

    {
      icon: <FaInstagram />,
      title: "Instagram",
      value: "@kingu_ai",
      subtitle: "Follow us for updates"
    }

  ];

  /* MAP CONTACT CARDS */

  const contacts = contactInfo.map((element, index) => (

    <div
      key={index}
      className="bg-white p-6 md:p-8 rounded-3xl shadow hover:shadow-2xl transition duration-300 flex flex-col sm:flex-row gap-6 items-start"
    >

      {/* ICON */}

      <div className="w-14 h-14 md:w-16 md:h-16 rounded-2xl bg-black text-white flex items-center justify-center text-xl md:text-2xl">

        {element.icon}

      </div>

      {/* TEXT */}

      <div>

        <h1 className="text-xl md:text-2xl font-bold mb-2">

          {element.title}

        </h1>

        <p className="text-gray-700 mb-2 break-all">

          {element.value}

        </p>

        <p className="text-gray-500 text-sm md:text-base">

          {element.subtitle}

        </p>

      </div>

    </div>

  ));

  /* FORM STATE */

  const [form, setForm] = useState({

    name: "",
    phone: "",
    email: "",
    subject: "",
    message: ""

  });

  const [loading, setLoading] = useState(false);
  const [status, setStatus] = useState({ type: "", message: "" });

  /* HANDLE CHANGE */

  const handleChange = (e) => {

    setForm({

      ...form,
      [e.target.name]: e.target.value

    });

  };

  /* HANDLE SUBMIT */

  const handleSubmit = async (e) => {

    e.preventDefault();
    setLoading(true);
    setStatus({ type: "", message: "" });

    try {
      const response = await fetch("/api/contact", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(form),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "Failed to submit message");
      }

      setStatus({ type: "success", message: "Message sent successfully!" });
      setForm({
        name: "",
        phone: "",
        email: "",
        subject: "",
        message: ""
      });
    } catch (err) {
      setStatus({ type: "error", message: err.message });
    } finally {
      setLoading(false);
    }

  };

  return (

    <div className="bg-[#f5f5f5] min-h-screen overflow-hidden">

      <Navbar />

      {/* HERO */}

      <section className="text-center py-20 md:py-28 px-5 md:px-10">

        <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-8">

          Let's Connect

        </h1>

        <p className="text-gray-600 text-base md:text-lg leading-7 md:leading-8 max-w-3xl mx-auto">

          Have a question about our programs?
          Ready to apply? Want to collaborate?
          We'd love to hear from you.

        </p>

      </section>

      {/* CONTACT SECTION */}

      <section className="px-5 md:px-10 pb-20 md:pb-28">

        <div className="grid grid-cols-1 md:grid-cols-2 gap-10 md:gap-20">

          {/* LEFT SIDE */}

          <div>

            <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-12">

              Get in Touch

            </h1>

            {/* CONTACT CARDS */}

            <div className="space-y-8">

              {contacts}

            </div>

            {/* LOCATION */}

            <div className="mt-16">

              <p className="tracking-widest text-gray-500 mb-5 text-sm">

                OUR LOCATION

              </p>

              <p className="text-gray-700 leading-7 md:leading-8">

Jaipur Rajasthan

              </p>

            </div>

          </div>

          {/* RIGHT SIDE FORM */}

          <div className="bg-white p-6 md:p-10 rounded-3xl shadow">

            <h1 className="text-3xl md:text-4xl font-bold mb-4">

              Send a Message

            </h1>

            <p className="text-gray-500 mb-10">

              We'll get back to you as soon as possible.

            </p>

            {status.message && (
              <div
                className={`p-4 rounded-2xl mb-6 text-center text-sm font-semibold border ${
                  status.type === "success"
                    ? "bg-green-50 text-green-600 border-green-200"
                    : "bg-red-50 text-red-600 border-red-200"
                }`}
              >
                {status.message}
              </div>
            )}

            {/* FORM */}

            <form
              onSubmit={handleSubmit}
              className="space-y-8"
            >

              {/* ROW 1 */}

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">

                <div>

                  <label className="block mb-3 font-medium">

                    Full Name

                  </label>

                  <input
                    type="text"
                    name="name"
                    value={form.name}
                    onChange={handleChange}
                    placeholder="John Doe"
                    className="w-full border border-gray-300 rounded-xl px-5 py-4 outline-none focus:border-black"
                  />

                </div>

                <div>

                  <label className="block mb-3 font-medium">

                    Phone

                  </label>

                  <input
                    type="text"
                    name="phone"
                    value={form.phone}
                    onChange={handleChange}
                    placeholder="+91 9876543210"
                    className="w-full border border-gray-300 rounded-xl px-5 py-4 outline-none focus:border-black"
                  />

                </div>

              </div>

              {/* ROW 2 */}

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">

                <div>

                  <label className="block mb-3 font-medium">

                    Email

                  </label>

                  <input
                    type="email"
                    name="email"
                    value={form.email}
                    onChange={handleChange}
                    placeholder="john@example.com"
                    className="w-full border border-gray-300 rounded-xl px-5 py-4 outline-none focus:border-black"
                  />

                </div>

                <div>

                  <label className="block mb-3 font-medium">

                    Subject

                  </label>

                  <input
                    type="text"
                    name="subject"
                    value={form.subject}
                    onChange={handleChange}
                    placeholder="General Inquiry"
                    className="w-full border border-gray-300 rounded-xl px-5 py-4 outline-none focus:border-black"
                  />

                </div>

              </div>

              {/* MESSAGE */}

              <div>

                <label className="block mb-3 font-medium">

                  Message

                </label>

                <textarea
                  rows="6"
                  name="message"
                  value={form.message}
                  onChange={handleChange}
                  placeholder="How can we help you?"
                  className="w-full border border-gray-300 rounded-xl px-5 py-4 outline-none focus:border-black resize-none"
                ></textarea>

              </div>

              {/* BUTTON */}

              <button
                type="submit"
                disabled={loading}
                className={`w-full bg-black text-white py-4 md:py-5 rounded-xl hover:bg-gray-800 transition font-semibold tracking-widest ${
                  loading ? "opacity-50 cursor-not-allowed" : ""
                }`}
              >

                {loading ? "SENDING..." : "SEND MESSAGE"}

              </button>

            </form>

          </div>

        </div>

      </section>

      {/* CTA SECTION */}

      <section className="bg-black text-white text-center py-20 md:py-28 px-5 md:px-10">

        <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-8">

          Book a Free Counseling Session

        </h1>

        <p className="text-gray-400 text-base md:text-lg leading-7 md:leading-8 max-w-2xl mx-auto">

          30-minute session with our admissions advisor
          to discuss your career path in AI.

        </p>

        <button className="mt-10 bg-white text-black px-6 md:px-10 py-3 md:py-4 rounded-xl font-semibold hover:bg-gray-200 transition">

          BOOK NOW

        </button>

      </section>

      {/* MAP SECTION */}

      <section className="px-5 md:px-10 py-20 md:py-28">

        <div className="grid grid-cols-1 md:grid-cols-2 gap-10 md:gap-20 items-center">

          {/* LEFT */}

          <div>

            <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-10">

              Find Us

            </h1>

            <p className="text-gray-700 leading-7 md:leading-8 mb-10">

               Divijix academy <br />
             Jaipur,Rajasthan

            </p>

            <div className="space-y-5">

              <div className="flex items-center gap-4">

                <FaMapMarkerAlt />

                <p>8009799550</p>

              </div>

              <div className="flex items-center gap-4">

                <FaPhoneAlt />

                <p>8009799550</p>

              </div>

            </div>

          </div>

          {/* RIGHT MAP */}

          <div className="bg-gray-300 h-[250px] md:h-[400px] rounded-3xl shadow-xl"></div>

        </div>

      </section>

      <Footer />

    </div>

  );
}

export default Contact;
