// src/pages/Login.jsx
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";

function Login() {
  const navigate = useNavigate();

  /* TOGGLE LOGIN / SIGNUP */

  const [isLogin, setIsLogin] = useState(true);

  /* FORM STATE */

  const [formData, setFormData] = useState({

    name: "",
    email: "",
    password: ""

  });

  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  /* HANDLE INPUT */

  const handleChange = (e) => {

    const { name, value } = e.target;

    setFormData({

      ...formData,
      [name]: value

    });

  };

  /* HANDLE SUBMIT */

  const handleSubmit = async (e) => {

    e.preventDefault();
    setError("");
    setLoading(true);

    const endpoint = isLogin ? "/api/auth/login" : "/api/auth/signup";

    try {
      const response = await fetch(endpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(formData),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "Authentication failed");
      }

      localStorage.setItem("token", data.token);
      localStorage.setItem("user", JSON.stringify(data.user));

      alert(isLogin ? "Login Successful" : "Account Created Successfully");
      navigate("/dashboard");
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }

  };

  return (

    <section className="min-h-screen bg-[#f8f8f8] flex justify-center items-center px-5 py-10">

      <div className="bg-white w-full max-w-md rounded-3xl shadow-2xl p-8 md:p-10">

        {/* TITLE */}

        <div className="text-center mb-10">

          <h1 className="text-4xl md:text-5xl font-bold">

            {isLogin ? "Welcome Back" : "Create Account"}

          </h1>

          <p className="text-gray-500 mt-4 text-base md:text-lg">

            {isLogin
              ? "Login to continue learning AI"
              : "Join divijixtechnology"}

          </p>

        </div>

        {/* ERROR DISPLAY */}
        {error && (
          <div className="bg-red-50 text-red-600 p-4 rounded-2xl mb-6 text-center text-sm font-semibold border border-red-200">
            {error}
          </div>
        )}


        {/* FORM */}

        <form
          onSubmit={handleSubmit}
          className="space-y-6"
        >

          {/* NAME */}

          {!isLogin && (

            <div>

              <label className="block mb-2 font-semibold text-lg">

                Full Name *

              </label>

              <input
                type="text"
                name="name"
                value={formData.name}
                onChange={handleChange}
                placeholder="Enter your full name"
                required
                className="w-full border border-gray-300 rounded-2xl px-5 py-4 text-lg outline-none focus:border-red-500"
              />

            </div>

          )}

          {/* EMAIL */}

          <div>

            <label className="block mb-2 font-semibold text-lg">

              Email *

            </label>

            <input
              type="email"
              name="email"
              value={formData.email}
              onChange={handleChange}
              placeholder="Enter your email"
              required
              className="w-full border border-gray-300 rounded-2xl px-5 py-4 text-lg outline-none focus:border-red-500"
            />

          </div>

          {/* PASSWORD */}

          <div>

            <label className="block mb-2 font-semibold text-lg">

              Password *

            </label>

            <input
              type="password"
              name="password"
              value={formData.password}
              onChange={handleChange}
              placeholder="Enter password"
              required
              className="w-full border border-gray-300 rounded-2xl px-5 py-4 text-lg outline-none focus:border-red-500"
            />

          </div>

          {/* BUTTON */}

          <button
            type="submit"
            disabled={loading}
            className={`w-full bg-red-600 text-white py-4 rounded-2xl hover:bg-red-700 transition duration-300 font-semibold text-xl ${
              loading ? "opacity-50 cursor-not-allowed" : ""
            }`}
          >

            {loading ? (isLogin ? "Logging in..." : "Creating Account...") : (isLogin ? "Login" : "Create Account")}

          </button>

        </form>

        {/* TOGGLE */}

        <div className="text-center mt-8">

          {isLogin ? (

            <p className="text-gray-600 text-lg">

              Don't have an account?{" "}

              <button
                onClick={() => setIsLogin(false)}
                className="text-red-600 font-bold"
              >

                Sign Up

              </button>

            </p>

          ) : (

            <p className="text-gray-600 text-lg">

              Already have an account?{" "}

              <button
                onClick={() => setIsLogin(true)}
                className="text-red-600 font-bold"
              >

                Sign In

              </button>

            </p>

          )}

        </div>

      </div>

    </section>

  );
}

export default Login;

// src/app/pages/login/login.component.ts
import { Component, inject } from '@angular/core';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ApiService } from '../../services/api.service';
import { AuthService } from '../../services/auth.service';

interface AuthResponse {
  token: string;
  user: any;
}

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './login.component.html'
})
export class LoginComponent {
  private apiService = inject(ApiService);
  private authService = inject(AuthService);
  private router = inject(Router);
  private fb = inject(FormBuilder);

  isLogin = true;
  loginForm: FormGroup = this.fb.group({
    name: [''],
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required, Validators.minLength(6)]]
  });

  error = '';
  loading = false;

  goHome() {
    this.router.navigate(['/']);
  }

  toggleMode() {
    this.isLogin = !this.isLogin;
    this.error = '';
    const nameControl = this.loginForm.get('name');
    if (this.isLogin) {
      nameControl?.clearValidators();
    } else {
      nameControl?.setValidators([Validators.required]);
    }
    nameControl?.updateValueAndValidity();
  }

  handleSubmit() {
    if (this.loginForm.invalid) {
      this.loginForm.markAllAsTouched();
      return;
    }

    this.error = '';
    this.loading = true;

    const endpoint = this.isLogin ? '/api/auth/login' : '/api/auth/signup';
    const payload = { ...this.loginForm.value };
    if (this.isLogin) {
      delete payload.name;
    }

    this.apiService.post<AuthResponse>(endpoint, payload).subscribe({
      next: (data) => {
        this.authService.login(data.user, data.token);
        alert(this.isLogin ? "Login Successful" : "Account Created Successfully");
        this.router.navigate(['/dashboard']);
        this.loading = false;
      },
      error: (err) => {
        this.error = err.error?.error || "Authentication failed";
        this.loading = false;
      }
    });
  }
}

<section
  class="min-h-screen bg-[#f8f8f8] dark:bg-[#080809] flex justify-center items-center px-5 py-10 text-gray-800 dark:text-white transition-colors duration-250">
  <div
    class="bg-white dark:bg-[#141416] border border-gray-100 dark:border-zinc-800/85 w-full max-w-md rounded-3xl shadow-2xl p-8 md:p-10 relative">
    <!-- BACK HOME LINK -->
    <button (click)="goHome()"
      class="absolute top-6 left-6 text-xs font-semibold hover:text-red-500 transition border-none bg-transparent cursor-pointer text-gray-400 dark:text-zinc-500 flex items-center gap-1">
      <i class="fa-solid fa-arrow-left"></i> Home
    </button>

    <!-- TITLE -->
    <div class="text-center mb-10 mt-4">
      <h1 class="text-4xl md:text-5xl font-bold text-gray-955 dark:text-white">
        {{isLogin ? 'Welcome Back' : 'Create Account'}}
      </h1>
      <p class="text-gray-500 dark:text-zinc-400 mt-4 text-base md:text-lg">
        {{isLogin ? 'Login to continue learning AI' : 'Join Divijix Technology'}}
      </p>
    </div>

    <!-- ERROR DISPLAY -->
    @if (error) {
    <div
      class="bg-red-50 text-red-655 dark:bg-red-950/20 dark:text-red-400 p-4 rounded-2xl mb-6 text-center text-sm font-semibold border border-red-200 dark:border-red-900/50">
      {{error}}
    </div>
    }

    <!-- FORM -->
    <form [formGroup]="loginForm" (ngSubmit)="handleSubmit()" class="space-y-6">
      <!-- NAME -->
      @if (!isLogin) {
      <div class="text-left">
        <label class="block mb-2 font-semibold text-lg text-gray-700 dark:text-zinc-300">
          Full Name *
        </label>
        <input type="text" formControlName="name" placeholder="Enter your full name"
          class="w-full bg-white dark:bg-[#0D0D0E] border border-gray-300 dark:border-zinc-800 rounded-2xl px-5 py-4 text-lg outline-none focus:border-red-500 text-gray-855 dark:text-white placeholder-gray-400" />
        @if (loginForm.get('name')?.touched && loginForm.get('name')?.errors?.['required']) {
        <p class="text-red-500 text-sm mt-1">Full name is required.</p>
        }
      </div>
      }

      <!-- EMAIL -->
      <div class="text-left">
        <label class="block mb-2 font-semibold text-lg text-gray-700 dark:text-zinc-300">
          Email *
        </label>
        <input type="email" formControlName="email" placeholder="Enter your email"
          class="w-full bg-white dark:bg-[#0D0D0E] border border-gray-300 dark:border-zinc-800 rounded-2xl px-5 py-4 text-lg outline-none focus:border-red-500 text-gray-855 dark:text-white placeholder-gray-400" />
        @if (loginForm.get('email')?.touched && loginForm.get('email')?.errors) {
        <p class="text-red-500 text-sm mt-1">
          @if (loginForm.get('email')?.errors?.['required']) {
          Email is required.
          } @else if (loginForm.get('email')?.errors?.['email']) {
          Please enter a valid email address.
          }
        </p>
        }
      </div>

      <!-- PASSWORD -->
      <div class="text-left">
        <label class="block mb-2 font-semibold text-lg text-gray-700 dark:text-zinc-300">
          Password *
        </label>
        <input type="password" formControlName="password" placeholder="Enter password"
          class="w-full bg-white dark:bg-[#0D0D0E] border border-gray-300 dark:border-zinc-800 rounded-2xl px-5 py-4 text-lg outline-none focus:border-red-500 text-gray-855 dark:text-white placeholder-gray-400" />
        @if (loginForm.get('password')?.touched && loginForm.get('password')?.errors) {
        <p class="text-red-500 text-sm mt-1">
          @if (loginForm.get('password')?.errors?.['required']) {
          Password is required.
          } @else if (loginForm.get('password')?.errors?.['minlength']) {
          Password must be at least 6 characters.
          }
        </p>
        }
      </div>

      <!-- BUTTON -->
      <button type="submit" [disabled]="loading"
        class="w-full bg-red-600 text-white py-4 rounded-2xl hover:bg-red-700 transition duration-300 font-semibold text-xl border-none cursor-pointer disabled:opacity-50">
        {{loading ? (isLogin ? 'Logging in...' : 'Creating Account...') : (isLogin ? 'Login' : 'Create Account')}}
      </button>
    </form>

    <!-- TOGGLE -->
    <div class="text-center mt-8">
      @if (isLogin) {
      <p class="text-gray-600 dark:text-zinc-400 text-lg">
        Don't have an account?
        <button (click)="toggleMode()"
          class="text-red-600 font-bold border-none bg-transparent cursor-pointer text-lg inline ml-1 hover:underline">
          Sign Up
        </button>
      </p>
      } @else {
      <p class="text-gray-600 dark:text-zinc-400 text-lg">
        Already have an account?
        <button (click)="toggleMode()"
          class="text-red-600 font-bold border-none bg-transparent cursor-pointer text-lg inline ml-1 hover:underline">
          Sign In
        </button>
      </p>
      }
    </div>
  </div>
</section>
