// src/app/components/cta/cta.component.ts
import { Component, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-cta',
  standalone: true,
  templateUrl: './cta.component.html'
})
export class CtaComponent {
  @Output() applyClicked = new EventEmitter<void>();
  @Output() demoClicked = new EventEmitter<void>();
}

<section class="relative px-6 md:px-16 py-24 bg-white dark:bg-[#0A0A0B] text-gray-800 dark:text-white transition-colors duration-250">
  
  <!-- Subtle Grid Background -->
  <div class="absolute inset-0 bg-[linear-gradient(to_right,#80808005_1px,transparent_1px),linear-gradient(to_bottom,#80808005_1px,transparent_1px)] bg-[size:30px_30px] pointer-events-none"></div>

  <div class="relative max-w-7xl mx-auto bg-gradient-to-br from-gray-950 via-slate-900 to-gray-950 dark:from-[#111112] dark:via-[#141416] dark:to-[#0D0D0E] border border-gray-800/80 dark:border-zinc-800/80 rounded-[2.5rem] p-8 md:p-16 flex flex-col lg:flex-row items-center justify-between shadow-2xl overflow-hidden">
    
    <!-- Glowing background decorative spheres -->
    <div class="absolute -right-20 -bottom-20 w-80 h-80 rounded-full bg-red-600/10 blur-[100px] pointer-events-none"></div>
    <div class="absolute -left-20 -top-20 w-80 h-80 rounded-full bg-rose-500/10 blur-[100px] pointer-events-none"></div>

    <!-- LEFT -->
    <div class="text-left lg:max-w-2xl relative z-10 space-y-6">
      <div class="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-red-500/10 border border-red-500/20">
        <span class="text-xs font-bold tracking-widest text-red-400 uppercase">
          Start Today
        </span>
      </div>
      <h2 class="text-4xl md:text-5xl font-black leading-tight text-white">
        Ready to Build <br />
        the Future?
      </h2>
      <p class="text-gray-400 text-base md:text-lg leading-relaxed">
        Join thousands of students and developers transforming their careers with practical AI, Cloud and Full-Stack training.
      </p>
    </div>

    <!-- BUTTONS -->
    <div class="flex gap-4 mt-10 lg:mt-0 flex-wrap relative z-10">
      <button (click)="applyClicked.emit()" 
        class="relative group overflow-hidden bg-gradient-to-r from-red-600 to-rose-600 text-white px-8 py-4 rounded-2xl hover:shadow-[0_0_30px_rgba(239,68,68,0.4)] transition-all duration-300 font-bold text-base cursor-pointer border-none">
        <span class="absolute inset-0 w-full h-full bg-gradient-to-r from-rose-600 to-red-600 opacity-0 group-hover:opacity-100 transition-opacity duration-300"></span>
        <span class="relative z-10">Apply Now</span>
      </button>
      <button (click)="demoClicked.emit()" 
        class="border border-zinc-700 text-zinc-300 px-8 py-4 rounded-2xl hover:bg-zinc-800 hover:text-white transition duration-300 font-bold text-base cursor-pointer bg-zinc-900/40 backdrop-blur-sm">
        Book Demo
      </button>
    </div>
  </div>
</section>

// src/components/CTA.jsx
import React from "react";

function CTA() {

  return (

    <section className="px-10 py-24 bg-[#f8f8f8]">

      <div className="bg-black text-white rounded-3xl p-14 flex flex-col md:flex-row items-center justify-between">

        {/* LEFT */}
        <div>

          <p className="text-red-500 font-semibold mb-3">
            START TODAY
          </p>

          <h1 className="text-4xl md:text-5xl font-bold leading-tight">
            Ready to Build <br />
            the Future?
          </h1>

          <p className="text-gray-400 mt-6 leading-7">
            Join thousands of students transforming
            their careers with AI.
          </p>

        </div>

        {/* BUTTONS */}
        <div className="flex gap-5 mt-10 md:mt-0">

          <button className="bg-red-600 px-7 py-3 rounded-xl hover:bg-red-700 transition">
            Apply Now
          </button>

          <button className="border border-white px-7 py-3 rounded-xl hover:bg-white hover:text-black transition">
            Book Demo
          </button>

        </div>

      </div>

    </section>

  );
}

export default CTA;
