// src/app/components/features/features.component.ts
import { Component } from '@angular/core';

interface Feature {
  iconClass: string;
  title: string;
  description: string;
}

@Component({
  selector: 'app-features',
  standalone: true,
  templateUrl: './features.component.html'
})
export class FeaturesComponent {
  features: Feature[] = [
    {
      iconClass: 'fa-solid fa-laptop-code',
      title: 'Industry-Ready Curriculum',
      description: 'Learn the most in-demand AI skills with practical training.'
    },
    {
      iconClass: 'fa-solid fa-diagram-project',
      title: 'Hands-on Projects',
      description: 'Build real-world AI applications and deploy solutions.'
    },
    {
      iconClass: 'fa-solid fa-user-graduate',
      title: 'Expert Mentorship',
      description: 'Get guidance from experienced AI engineers and mentors.'
    },
    {
      iconClass: 'fa-solid fa-flask',
      title: 'Research-Oriented',
      description: 'Explore advanced AI technologies and innovations.'
    }
  ];
}

<section class="relative bg-slate-50 dark:bg-[#080809] text-gray-800 dark:text-white px-6 md:px-16 py-24 transition-colors duration-250">
  
  <!-- Glowing Background Orb -->
  <div class="absolute bottom-1/4 left-10 w-80 h-80 rounded-full bg-red-600/5 dark:bg-red-500/[0.02] blur-[90px] pointer-events-none"></div>

  <!-- TITLE -->
  <div class="text-center mb-16 space-y-4">
    <p class="text-red-600 dark:text-red-500 font-extrabold text-xs md:text-sm tracking-widest uppercase">
      Why Choose Us
    </p>
    <h2 class="text-3xl md:text-4xl lg:text-5xl font-black tracking-tight text-gray-950 dark:text-white">
      The Divijix Academy Difference
    </h2>
    <div class="w-12 h-1 bg-red-600 dark:bg-red-500 mx-auto rounded-full"></div>
  </div>

  <!-- FEATURE CARDS -->
  <div class="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
    @for (item of features; track $index) {
      <div class="group relative bg-white dark:bg-[#111112] p-8 rounded-[2rem] border border-gray-200/60 dark:border-zinc-800/80 hover:border-red-500/30 dark:hover:border-red-500/20 hover:shadow-[0_20px_50px_rgba(239,68,68,0.05)] hover:-translate-y-1.5 transition-all duration-300 min-h-[320px] flex flex-col justify-between overflow-hidden">
        
        <!-- Hover Glow Border -->
        <div class="absolute -inset-px rounded-[2rem] bg-gradient-to-tr from-red-600 to-rose-500 opacity-0 group-hover:opacity-10 transition-opacity duration-300 pointer-events-none"></div>

        <div>
          <!-- ICON -->
          <div class="inline-flex items-center justify-center w-14 h-14 rounded-2xl bg-red-50 dark:bg-red-950/20 text-red-600 dark:text-red-500 mb-8 group-hover:scale-110 group-hover:bg-red-600 group-hover:text-white transition-all duration-300 text-3xl">
            <i [class]="item.iconClass"></i>
          </div>

          <!-- TITLE -->
          <h3 class="text-xl font-bold mb-4 text-gray-955 dark:text-white">
            {{item.title}}
          </h3>

          <!-- DESCRIPTION -->
          <p class="text-gray-600 dark:text-zinc-400 leading-relaxed text-sm">
            {{item.description}}
          </p>
        </div>
      </div>
    }
  </div>
</section>

// src/components/Features.jsx
import React from 'react'
import {
  FaLaptopCode,
  FaProjectDiagram,
  FaUserGraduate,
  FaFlask
} from "react-icons/fa";

const features = [

  {
    icon: <FaLaptopCode />,
    title: "Industry-Ready Curriculum",
    description:
      "Learn the most in-demand AI skills with practical training."
  },

  {
    icon: <FaProjectDiagram />,
    title: "Hands-on Projects",
    description:
      "Build real-world AI applications and deploy solutions."
  },

  {
    icon: <FaUserGraduate />,
    title: "Expert Mentorship",
    description:
      "Get guidance from experienced AI engineers and mentors."
  },

  {
    icon: <FaFlask />,
    title: "Research-Oriented",
    description:
      "Explore advanced AI technologies and innovations."
  }

];

const labels = features.map((item, index) => (

  <div
    key={index}
    className="bg-[#111111] p-8 rounded-3xl border border-gray-800 hover:border-red-600 hover:shadow-red-500/20 hover:shadow-2xl transition duration-300 min-h-[320px]"
  >

    {/* ICON */}
    <div className="text-5xl text-red-500 mb-6">
      {item.icon}
    </div>

    {/* TITLE */}
    <h1 className="text-2xl font-bold mb-4">
      {item.title}
    </h1>

    {/* DESCRIPTION */}
    <p className="text-gray-400 leading-7">
      {item.description}
    </p>

  </div>

));

function Features() {

  return (

    <section className="bg-black text-white px-10 py-24">

      {/* TITLE */}
      <div className="text-center mb-16">

        <p className="text-red-500 font-semibold mb-3">
          WHY CHOOSE US
        </p>

        <h1 className="text-4xl md:text-5xl font-bold">
          The  Divijix academy Difference
        </h1>

      </div>

      {/* FEATURE CARDS */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">

        {labels}

      </div>

    </section>

  )
}

export default Features
