// src/app/components/hero/hero.component.ts
import { Component, Output, EventEmitter, inject } from '@angular/core';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-hero',
  standalone: true,
  imports: [ReactiveFormsModule],
  templateUrl: './hero.component.html'
})
export class HeroComponent {
  @Output() applyClicked = new EventEmitter<void>();
  @Output() exploreClicked = new EventEmitter<void>();
  
  private fb = inject(FormBuilder);

  openForm = false;
  
  enquiryForm: FormGroup = this.fb.group({
    phone: ['', [Validators.required, Validators.pattern('^[0-9]{10}$')]],
    email: ['', [Validators.required, Validators.email]],
    message: ['', Validators.required]
  });

  handleSubmit() {
    if (this.enquiryForm.invalid) {
      this.enquiryForm.markAllAsTouched();
      return;
    }

    console.log(this.enquiryForm.value);
    alert("Enquiry Submitted Successfully 🚀");
    this.enquiryForm.reset();
    this.openForm = false;
  }
}

<section
  class="relative min-h-[85vh] flex items-center px-6 md:px-16 py-20 bg-gradient-to-b from-slate-50 to-white dark:from-[#080809] dark:to-[#020203] overflow-hidden text-gray-800 dark:text-white transition-colors duration-250">
  
  <!-- Glowing Background Orbs -->
  <div class="absolute top-1/4 left-1/4 -translate-x-1/2 -translate-y-1/2 w-72 h-72 rounded-full bg-red-500/10 dark:bg-red-500/5 blur-[100px] pointer-events-none"></div>
  <div class="absolute bottom-10 right-10 w-96 h-96 rounded-full bg-red-600/10 dark:bg-red-600/5 blur-[120px] pointer-events-none"></div>
  
  <!-- Subtle Grid Background -->
  <div class="absolute inset-0 bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:24px_24px] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_100%)] pointer-events-none"></div>

  <div class="max-w-7xl mx-auto w-full grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-16 items-center relative z-10">
    <!-- LEFT SIDE -->
    <div class="text-left lg:col-span-7 space-y-8">
      <!-- Badge -->
      <div class="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-red-50 dark:bg-red-950/20 border border-red-200/50 dark:border-red-900/30">
        <span class="w-2 h-2 rounded-full bg-red-600 dark:bg-red-500 animate-pulse"></span>
        <span class="text-xs md:text-sm font-bold tracking-wide text-red-650 dark:text-red-400 uppercase">
          India's Premier AI & Tech Institute
        </span>
      </div>

      <h1 class="text-4xl md:text-5xl lg:text-6xl font-black tracking-tight leading-[1.1] text-gray-950 dark:text-white">
        Build the Future <br />
        with <span class="bg-gradient-to-r from-red-600 to-rose-500 bg-clip-text text-transparent dark:from-red-500 dark:to-rose-400">Internship Training</span>
      </h1>
      
      <p class="text-gray-600 dark:text-zinc-400 text-base md:text-lg leading-relaxed max-w-2xl">
        Master Artificial Intelligence, Machine Learning, Data Science, Generative AI, and Cloud Computing at Divijix.
        Gain hands-on experience through industry-ready curriculum, expert mentorship, and real-world projects.
      </p>

      <!-- BUTTONS -->
      <div class="flex flex-wrap gap-4 pt-2">
        <button (click)="applyClicked.emit()"
          class="relative group overflow-hidden bg-gradient-to-r from-red-600 to-rose-600 text-white px-8 py-4 rounded-2xl hover:shadow-[0_0_30px_rgba(239,68,68,0.4)] transition-all duration-300 font-bold text-base cursor-pointer border-none">
          <span class="absolute inset-0 w-full h-full bg-gradient-to-r from-rose-600 to-red-600 opacity-0 group-hover:opacity-100 transition-opacity duration-300"></span>
          <span class="relative z-10 flex items-center gap-2">
            Apply Now <i class="fa-solid fa-arrow-right text-sm transition-transform group-hover:translate-x-1"></i>
          </span>
        </button>
        <button (click)="exploreClicked.emit()"
          class="border border-gray-300 dark:border-zinc-800 text-gray-700 dark:text-zinc-200 px-8 py-4 rounded-2xl hover:bg-gray-100 dark:hover:bg-zinc-850 hover:text-gray-955 dark:hover:text-white transition duration-300 font-bold text-base cursor-pointer bg-white/50 dark:bg-zinc-900/30 backdrop-blur-sm">
          Explore Courses
        </button>
        <button (click)="openForm = true"
          class="border border-gray-300 dark:border-zinc-800 text-gray-700 dark:text-zinc-200 px-8 py-4 rounded-2xl hover:bg-gray-100 dark:hover:bg-zinc-850 hover:text-gray-955 dark:hover:text-white transition duration-300 font-bold text-base cursor-pointer bg-white/50 dark:bg-zinc-900/30 backdrop-blur-sm">
          Enquiry Now
        </button>
      </div>

      <!-- STATS -->
      <div class="grid grid-cols-3 gap-6 md:gap-10 pt-6 border-t border-gray-200/50 dark:border-zinc-800/50 max-w-xl">
        <div class="space-y-1">
          <h2 class="text-3xl md:text-4xl font-extrabold text-gray-950 dark:text-white">
            15+
          </h2>
          <p class="text-gray-400 dark:text-zinc-500 text-[11px] md:text-xs uppercase tracking-wider font-bold">
            Programs
          </p>
        </div>
        <div class="space-y-1">
          <h2 class="text-3xl md:text-4xl font-extrabold text-gray-955 dark:text-white">
            50+
          </h2>
          <p class="text-gray-400 dark:text-zinc-500 text-[11px] md:text-xs uppercase tracking-wider font-bold">
            Projects
          </p>
        </div>
        <div class="space-y-1">
          <h2 class="text-3xl md:text-4xl font-extrabold text-gray-955 dark:text-white">
            95%
          </h2>
          <p class="text-gray-400 dark:text-zinc-500 text-[11px] md:text-xs uppercase tracking-wider font-bold">
            Outcomes
          </p>
        </div>
      </div>
    </div>

    <!-- RIGHT SIDE HERO CARD/IMAGE -->
    <div class="lg:col-span-5 flex justify-center relative">
      <!-- Glow effect behind image -->
      <div class="absolute -inset-1 rounded-[2.5rem] bg-gradient-to-tr from-red-600 to-rose-500 opacity-20 dark:opacity-30 blur-lg pointer-events-none"></div>
      
      <div class="relative bg-white dark:bg-[#141416] p-3 rounded-[2.5rem] border border-gray-200 dark:border-zinc-800 shadow-2xl overflow-hidden max-w-[440px] w-full aspect-square md:aspect-auto flex justify-center items-center">
        <img src="assets/images.jpg" alt="AI Hero"
          class="w-full h-full object-cover rounded-[2rem] transition-transform duration-500 hover:scale-[1.02]" />
      </div>
    </div>
  </div>
</section>

<!-- ENQUIRY FORM MODAL -->
@if (openForm) {
<div class="fixed inset-0 bg-black/60 dark:bg-black/80 flex justify-center items-center z-50 px-4 backdrop-blur-sm">
  <div
    class="bg-white dark:bg-[#141416] border border-gray-200 dark:border-zinc-800/80 text-gray-800 dark:text-white w-full max-w-lg rounded-3xl p-6 md:p-10 relative shadow-2xl">
    <!-- CLOSE BUTTON -->
    <button (click)="openForm = false"
      class="absolute top-5 right-5 text-2xl text-gray-400 hover:text-gray-600 dark:text-zinc-400 dark:hover:text-white transition cursor-pointer border-none bg-transparent">
      ✕
    </button>

    <!-- TITLE -->
    <h1 class="text-3xl font-bold mb-2 text-gray-955 dark:text-white">
      Quick Enquiry
    </h1>
    <p class="text-gray-550 dark:text-zinc-400 mb-8">
      Fill your details and our team will contact you.
    </p>

    <!-- FORM -->
    <form [formGroup]="enquiryForm" (ngSubmit)="handleSubmit()" class="space-y-6">
      <!-- PHONE NUMBER -->
      <div class="text-left">
        <label class="block mb-2 font-medium text-sm text-gray-700 dark:text-zinc-300">
          Phone Number *
        </label>
        <input type="text" formControlName="phone" placeholder="9876543210"
          class="w-full bg-white dark:bg-[#0D0D0E] border border-gray-300 dark:border-zinc-800 rounded-xl px-5 py-4 outline-none focus:border-red-500 focus:ring-1 focus:ring-red-500 text-sm text-gray-855 dark:text-white placeholder-gray-400 dark:placeholder-zinc-500" />
        @if (enquiryForm.get('phone')?.touched && enquiryForm.get('phone')?.errors) {
          <p class="text-red-500 text-xs mt-1">
            @if (enquiryForm.get('phone')?.errors?.['required']) {
              Phone number is required.
            } @else if (enquiryForm.get('phone')?.errors?.['pattern']) {
              Please enter a valid 10-digit phone number.
            }
          </p>
        }
      </div>

      <!-- EMAIL -->
      <div class="text-left">
        <label class="block mb-2 font-medium text-sm text-gray-700 dark:text-zinc-300">
          Email *
        </label>
        <input type="email" formControlName="email" placeholder="name@example.com"
          class="w-full bg-white dark:bg-[#0D0D0E] border border-gray-300 dark:border-zinc-800 rounded-xl px-5 py-4 outline-none focus:border-red-500 focus:ring-1 focus:ring-red-500 text-sm text-gray-855 dark:text-white placeholder-gray-400 dark:placeholder-zinc-500" />
        @if (enquiryForm.get('email')?.touched && enquiryForm.get('email')?.errors) {
          <p class="text-red-500 text-xs mt-1">
            @if (enquiryForm.get('email')?.errors?.['required']) {
              Email is required.
            } @else if (enquiryForm.get('email')?.errors?.['email']) {
              Please enter a valid email address.
            }
          </p>
        }
      </div>

      <!-- MESSAGE -->
      <div class="text-left">
        <label class="block mb-2 font-medium text-sm text-gray-700 dark:text-zinc-300">
          Message *
        </label>
        <textarea formControlName="message" rows="5" placeholder="Enter your enquiry message..."
          class="w-full bg-white dark:bg-[#0D0D0E] border border-gray-300 dark:border-zinc-800 rounded-xl px-5 py-4 outline-none resize-none focus:border-red-500 focus:ring-1 focus:ring-red-500 text-sm text-gray-855 dark:text-white placeholder-gray-400 dark:placeholder-zinc-500"></textarea>
        @if (enquiryForm.get('message')?.touched && enquiryForm.get('message')?.errors?.['required']) {
          <p class="text-red-500 text-xs mt-1">Message is required.</p>
        }
      </div>

      <!-- SUBMIT -->
      <button type="submit"
        class="w-full bg-red-600 text-white py-4 rounded-xl hover:bg-red-500 hover:shadow-[0_0_20px_rgba(239,68,68,0.4)] transition duration-300 font-semibold text-sm shadow-sm cursor-pointer border-none">
        Submit Enquiry
      </button>
    </form>
  </div>
</div>
}

// src/components/Hero.jsx
import { useState } from "react";

import comp from "../assets/images.jpg";

function Hero() {

  /* ENQUIRY MODAL STATE */

  const [openForm, setOpenForm] = useState(false);

  /* FORM STATE */

  const [formData, setFormData] = useState({

    phone: "",
    message: "",
    email: " "

  });

  /* HANDLE INPUT */

  const handleChange = (e) => {

    const { name, value } = e.target;

    setFormData({

      ...formData,
      [name]: value

    });

  };

  /* HANDLE SUBMIT */

  const handleSubmit = (e) => {

    e.preventDefault();

    console.log(formData);

    alert("Enquiry Submitted Successfully 🚀");

    setOpenForm(false);

  };

  return (

    <>

      <section className="grid grid-cols-1 md:grid-cols-2 items-center gap-12 md:gap-14 px-5 md:px-10 py-16 md:py-20 bg-[#f8f8f8] overflow-hidden">

        {/* LEFT SIDE */}

        <div>

          <p className="text-red-500 font-medium mb-4 text-sm md:text-base">

            India's Premier AI Training Institute

          </p>

          <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold leading-tight">

            Build the Future <br />

            with{" "}

            <span className="text-red-600">

              Artificial Intelligence

            </span>

          </h1>

          <p className="text-gray-600 mt-6 text-base md:text-lg leading-7 md:leading-8">

            Master AI, ML, Data Science, Generative AI,
            and Cloud Computing at Kingu.
            Industry-ready curriculum, expert mentors,
            real-world projects.

          </p>

          {/* BUTTONS */}

          <div className="flex flex-wrap gap-5 mt-10">

            <button className="bg-red-600 text-white px-6 md:px-7 py-3 rounded-lg hover:bg-red-700 transition duration-300">

              Apply Now →

            </button>

            <button className="border border-black px-6 md:px-7 py-3 rounded-lg hover:bg-black hover:text-white transition duration-300">

              Explore Courses

            </button>

          </div>

          {/* STATS */}

          <div className="flex flex-wrap gap-10 md:gap-16 mt-14">

            <div>

              <h1 className="text-3xl md:text-4xl font-bold">

                15+

              </h1>

              <p className="text-gray-500 mt-2 text-sm md:text-base">

                PROGRAMS

              </p>

            </div>

            <div>

              <h1 className="text-3xl md:text-4xl font-bold">

                50+

              </h1>

              <p className="text-gray-500 mt-2 text-sm md:text-base">

                PROJECTS

              </p>

            </div>

            <div>

              <h1 className="text-3xl md:text-4xl font-bold">

                95%

              </h1>

              <p className="text-gray-500 mt-2 text-sm md:text-base">

                OUTCOMES

              </p>

            </div>

          </div>

          {/* ENQUIRY BUTTON */}

          <div className="flex flex-wrap gap-5 mt-10">

            <button
              onClick={() => setOpenForm(true)}
              className="border border-black px-6 md:px-7 py-3 rounded-lg hover:bg-black hover:text-white transition duration-300"
            >

              Enquiry Now →

            </button>

          </div>

        </div>

        {/* RIGHT SIDE IMAGE */}

        <div className="flex justify-center">

          <img
            src={comp}
            alt="AI Hero"
            className="w-full max-w-[500px] h-[300px] md:h-auto object-cover rounded-3xl shadow-2xl border-4 border-white"
          />

        </div>

      </section>

      {/* ENQUIRY FORM MODAL */}

      {openForm && (

        <div className="fixed inset-0 bg-black/60 flex justify-center items-center z-50 px-4">

          <div className="bg-white w-full max-w-lg rounded-3xl p-6 md:p-10 relative">

            {/* CLOSE BUTTON */}

            <button
              onClick={() => setOpenForm(false)}
              className="absolute top-5 right-5 text-2xl"
            >

              ✕

            </button>

            {/* TITLE */}

            <h1 className="text-3xl font-bold mb-2">

              Quick Enquiry

            </h1>

            <p className="text-gray-500 mb-8">

              Fill your details and our team will contact you.

            </p>

            {/* FORM */}

            <form
              onSubmit={handleSubmit}
              className="space-y-6"
            >

              {/* PHONE NUMBER */}

              <div>

                <label className="block mb-2 font-medium">

                  Phone Number *

                </label>

                <input
                  type="text"
                  name="phone"
                  value={formData.phone}
                  onChange={handleChange}
                  placeholder="+91 9876543210"
                  required
                  className="w-full border border-gray-300 rounded-xl px-5 py-4 outline-none focus:border-red-500"
                />

              </div>
               <div>

                <label className="block mb-2 font-medium">

                  e-mail *

                </label>

                <input
                  type="email"
                  name="email"
                  value={formData.email}
                  onChange={handleChange}
                  placeholder="@gmail.com"
                  required
                  className="w-full border border-gray-300 rounded-xl px-5 py-4 outline-none focus:border-red-500"
                />

              </div>

              {/* MESSAGE */}

              <div>

                <label className="block mb-2 font-medium">

                  Message *

                </label>

                <textarea
                  name="message"
                  value={formData.message}
                  onChange={handleChange}
                  rows="5"
                  placeholder="Enter your enquiry message..."
                  required
                  className="w-full border border-gray-300 rounded-xl px-5 py-4 outline-none resize-none focus:border-red-500"
                ></textarea>

              </div>

              {/* SUBMIT */}

              <button
                type="submit"
                className="w-full bg-red-600 text-white py-4 rounded-xl hover:bg-red-700 transition duration-300 font-semibold"
              >

                Submit Enquiry 

              </button>

            </form>

          </div>

        </div>

      )}

    </>

  );
}

export default Hero;
