// src/app/components/stats/stats.component.ts
import { Component } from '@angular/core';

interface Stat {
  number: string;
  title: string;
  description: string;
}

@Component({
  selector: 'app-stats',
  standalone: true,
  templateUrl: './stats.component.html'
})
export class StatsComponent {
  courses: Stat[] = [
    {
      number: "$1.8T",
      title: "Global AI Market by 2030",
      description: "Artificial Intelligence is becoming the world's largest technology revolution."
    },
    {
      number: "97M",
      title: "New AI Jobs",
      description: "Millions of AI and Data Science jobs are expected worldwide."
    },
    {
      number: "3-5x",
      title: "Salary Growth",
      description: "AI Engineers earn significantly higher salaries than traditional roles."
    }
  ];
}

<section class="relative px-6 md:px-16 py-24 bg-white dark:bg-[#0A0A0B] overflow-hidden text-gray-800 dark:text-white transition-colors duration-250">
  
  <!-- Subtle Gradient Background -->
  <div class="absolute top-0 right-0 w-80 h-80 rounded-full bg-red-500/5 dark:bg-red-500/[0.02] blur-[80px] pointer-events-none"></div>

  <!-- TITLE -->
  <div class="text-center mb-16 space-y-4">
    <p class="text-red-600 dark:text-red-500 font-extrabold text-xs md:text-sm tracking-widest uppercase">
      Why AI Matters
    </p>
    <h2 class="text-3xl md:text-4xl lg:text-5xl font-black tracking-tight text-gray-950 dark:text-white">
      The AI Revolution
    </h2>
    <div class="w-12 h-1 bg-red-600 dark:bg-red-500 mx-auto rounded-full"></div>
  </div>

  <!-- CARDS -->
  <div class="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
    @for (item of courses; track $index) {
      <div class="group relative bg-[#f9fafb] dark:bg-[#111112] p-8 md:p-10 rounded-[2rem] border border-gray-200/60 dark:border-zinc-800/80 shadow-sm hover:shadow-[0_20px_50px_rgba(239,68,68,0.05)] hover:border-red-500/30 dark:hover:border-red-500/20 hover:-translate-y-1.5 transition-all duration-300 flex flex-col justify-between">
        
        <!-- Hover Glow Border -->
        <div class="absolute -inset-px rounded-[2rem] bg-gradient-to-tr from-red-600 to-rose-500 opacity-0 group-hover:opacity-10 transition-opacity duration-300 pointer-events-none"></div>

        <div>
          <!-- NUMBER -->
          <div class="flex items-center justify-between">
            <h1 class="text-5xl font-black bg-gradient-to-r from-red-600 to-rose-500 bg-clip-text text-transparent dark:from-red-500 dark:to-rose-400 group-hover:scale-105 transition-transform duration-300">
              {{item.number}}
            </h1>
            <span class="text-red-600/10 dark:text-red-500/10 text-4xl font-extrabold select-none"><i class="fa-solid fa-chart-line"></i></span>
          </div>

          <!-- TITLE -->
          <h3 class="text-xl md:text-2xl font-bold mt-8 leading-snug text-gray-950 dark:text-white">
            {{item.title}}
          </h3>

          <!-- DESCRIPTION -->
          <p class="text-gray-600 dark:text-zinc-400 mt-4 leading-relaxed text-sm md:text-base">
            {{item.description}}
          </p>
        </div>
      </div>
    }
  </div>
</section>

// src/components/Stats.jsx
import React from 'react'

const courses = [

  {
    number: "$1.8T",
    title: "Global AI Market by 2030",
    description:
      "Artificial Intelligence is becoming the world's largest technology revolution."
  },

  {
    number: "97M",
    title: "New AI Jobs",
    description:
      "Millions of AI and Data Science jobs are expected worldwide."
  },

  {
    number: "3-5x",
    title: "Salary Growth",
    description:
      "AI Engineers earn significantly higher salaries than traditional roles."
  },

]

function Stats() {

  const products = courses.map((item, index) => (

    <div
      key={index}
      className="bg-[#f8f8f8] p-6 md:p-10 rounded-3xl shadow hover:shadow-2xl transition duration-300"
    >

      {/* NUMBER */}

      <h1 className="text-4xl md:text-5xl font-bold text-red-600">

        {item.number}

      </h1>

      {/* TITLE */}

      <h2 className="text-xl md:text-2xl font-semibold mt-6 leading-snug">

        {item.title}

      </h2>

      {/* DESCRIPTION */}

      <p className="text-gray-600 mt-4 leading-7 text-sm md:text-base">

        {item.description}

      </p>

    </div>

  ))

  return (

    <section className="px-5 md:px-10 py-20 md:py-24 bg-white overflow-hidden">

      {/* TITLE */}

      <div className="text-center mb-16">

        <p className="text-red-500 font-semibold mb-3 text-sm md:text-base">

          WHY AI MATTERS

        </p>

        <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold leading-tight">

          The AI Revolution

        </h1>

      </div>

      {/* CARDS */}

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8">

        {products}

      </div>

    </section>

  )

}

export default Stats;
