// src/components/Testimonials.jsx
import React from "react";

const reviews = [

  {
    name: "Priya Sharma",
    role: "AI Engineer",
    review:
      "The programs completely changed my career. I landed my dream AI job within months."
  },

  {
    name: "Rahul Verma",
    role: "ML Developer",
    review:
      "Hands-on projects and mentorship helped me build real-world AI applications."
  },

  {
    name: "Anjali Patel",
    role: "Data Scientist",
    review:
      "The curriculum is industry-ready and very practical for beginners."
  }

];

function Testimonials() {

  return (

    <section className="px-5 md:px-10 py-20 md:py-24 bg-[#f8f8f8] overflow-hidden">

      {/* TITLE */}

      <div className="text-center mb-16">

        <p className="text-red-500 font-semibold mb-3 text-sm md:text-base">

          SUCCESS STORIES

        </p>

        <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold leading-tight">

          Real Results, Real Careers

        </h1>

      </div>

      {/* CARDS */}

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8">

        {reviews.map((item, index) => (

          <div
            key={index}
            className="bg-white p-6 md:p-8 rounded-3xl shadow hover:shadow-2xl transition duration-300 hover:-translate-y-2"
          >

            {/* NAME */}

            <h1 className="text-xl md:text-2xl font-bold mb-2">

              {item.name}

            </h1>

            {/* ROLE */}

            <p className="text-red-500 mb-6 text-sm md:text-base">

              {item.role}

            </p>

            {/* REVIEW */}

            <p className="text-gray-600 leading-7 text-sm md:text-base">

              "{item.review}"

            </p>

          </div>

        ))}

      </div>

    </section>

  );

}

export default Testimonials;

// src/app/components/testimonials/testimonials.component.ts
import { Component } from '@angular/core';

interface Review {
  name: string;
  role: string;
  review: string;
}

@Component({
  selector: 'app-testimonials',
  standalone: true,
  templateUrl: './testimonials.component.html'
})
export class TestimonialsComponent {
  reviews: Review[] = [
    {
      name: "Priya Sharma",
      role: "AI Engineer",
      review: "The programs completely changed my career. I landed my dream AI job within months."
    },
    {
      name: "Rahul Verma",
      role: "ML Developer",
      review: "Hands-on projects and mentorship helped me build real-world AI applications."
    },
    {
      name: "Anjali Patel",
      role: "Data Scientist",
      review: "The curriculum is industry-ready and very practical for beginners."
    }
  ];
}

<section class="relative px-6 md:px-16 py-24 bg-slate-50 dark:bg-[#080809] overflow-hidden text-gray-800 dark:text-white transition-colors duration-250">
  
  <!-- Glowing Background Orb -->
  <div class="absolute bottom-1/3 right-10 w-80 h-80 rounded-full bg-red-600/5 dark:bg-red-500/[0.02] blur-[90px] pointer-events-none"></div>

  <!-- TITLE -->
  <div class="text-center mb-16 space-y-4">
    <p class="text-red-655 dark:text-red-500 font-extrabold text-xs md:text-sm tracking-widest uppercase">
      Success Stories
    </p>
    <h2 class="text-3xl md:text-4xl lg:text-5xl font-black tracking-tight text-gray-955 dark:text-white">
      Real Results, Real Careers
    </h2>
    <div class="w-12 h-1 bg-red-600 dark:bg-red-500 mx-auto rounded-full"></div>
  </div>

  <!-- CARDS -->
  <div class="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
    @for (item of reviews; track $index) {
      <div class="group relative bg-white dark:bg-[#111112] border border-gray-200/60 dark:border-zinc-800/80 p-8 rounded-[2rem] hover:border-red-500/30 dark:hover:border-red-500/20 hover:shadow-[0_20px_50px_rgba(239,68,68,0.05)] hover:-translate-y-1.5 transition-all duration-300 flex flex-col justify-between overflow-hidden">
        
        <!-- Hover Glow Border -->
        <div class="absolute -inset-px rounded-[2rem] bg-gradient-to-tr from-red-600 to-rose-500 opacity-0 group-hover:opacity-10 transition-opacity duration-300 pointer-events-none"></div>

        <div>
          <!-- Rating & Quote Icon -->
          <div class="flex items-center justify-between mb-6">
            <div class="flex gap-1 text-amber-500 text-sm">
              <i class="fa-solid fa-star"></i>
              <i class="fa-solid fa-star"></i>
              <i class="fa-solid fa-star"></i>
              <i class="fa-solid fa-star"></i>
              <i class="fa-solid fa-star"></i>
            </div>
            <span class="text-red-600/10 dark:text-red-500/10 text-3xl select-none"><i class="fa-solid fa-quote-right"></i></span>
          </div>

          <!-- REVIEW -->
          <p class="text-gray-600 dark:text-zinc-350 leading-relaxed text-sm md:text-base italic mb-8">
            "{{item.review}}"
          </p>
        </div>

        <!-- USER DETAIL -->
        <div class="pt-6 border-t border-gray-200/40 dark:border-zinc-800/50 flex items-center gap-4">
          <div class="w-10 h-10 rounded-full bg-red-50 dark:bg-red-950/20 text-red-600 dark:text-red-500 flex items-center justify-center font-black uppercase text-sm border border-red-200/30 dark:border-red-900/30">
            {{item.name.charAt(0)}}
          </div>
          <div class="text-left">
            <h4 class="font-bold text-gray-955 dark:text-white leading-tight">{{item.name}}</h4>
            <p class="text-red-600 dark:text-red-500 text-xs font-semibold mt-0.5">
              {{item.role}}
            </p>
          </div>
        </div>
      </div>
    }
  </div>
</section>
